const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const dbPath = path.resolve(__dirname, 'database.sqlite');

const db = new sqlite3.Database(dbPath, (err) => {
  if (err) {
    console.error('Erreur lors de l\'ouverture de la base de données :', err.message);
  } else {
    console.log('Connecté à la base de données SQLite.');
    createTables();
  }
});

function createTables() {
  const dropTablesQueryLogs = `
    DROP TABLE IF EXISTS Logs;
  `;
  const dropTablesQueryEntity = `
    DROP TABLE IF EXISTS Entity;
  `;
  const dropTablesQueryRequest = `
    DROP TABLE IF EXISTS Request;
  `;
  const dropTablesQueryForm = `
    DROP TABLE IF EXISTS Form;
  `;
  const createTableQueryLogs = `
    CREATE TABLE IF NOT EXISTS Logs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      Titre TEXT NOT NULL,
      Description TEXT NOT NULL
    );
  `;
  const createTableQueryEntity = `
    CREATE TABLE IF NOT EXISTS Entity (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      Name TEXT NOT NULL,
      Licence TEXT NOT NULL,
      Image TEXT NOT NULL
    );
  `;
  const createTableQueryRequest = `
    CREATE TABLE IF NOT EXISTS Request (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      Title TEXT NOT NULL,
      SQL_Request TEXT NOT NULL,
      Image TEXT NOT NULL
    );
  `;
  const createTableQueryForm = `
    CREATE TABLE IF NOT EXISTS Form (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      Title TEXT NOT NULL,
      Option TEXT NOT NULL,
      Text TEXT NOT NULL
    );
  `;

  db.serialize(() => {
    // Supprimer les tables existantes
    db.run(dropTablesQueryLogs, (err) => {
      if (err) {
        console.error('Erreur lors de la suppression des logs :', err.message);
      } else {
        console.log('Tables Logs supprimée avec succès.');

        db.run(dropTablesQueryEntity, (err) => {
          if (err) {
            console.error('Erreur lors de la suppression des entités :', err.message);
          } else {
            console.log('Table Entity supprimée avec succès.');

            db.run(dropTablesQueryRequest, (err) => {
              if (err) {
                console.error('Erreur lors de la suppression des requêtes :', err.message);
              } else {
                console.log('Table Request supprimée avec succès.');


                db.run(dropTablesQueryForm, (err) => {
                  if (err) {
                    console.error('Erreur lors de la suppression des formulaires :', err.message);
                  } else {
                    console.log('Table Form supprimée avec succès.');
  
                    db.run(createTableQueryLogs, (err) => {
                      if (err) {
                        console.error('Erreur lors de la création de la table Logs :', err.message);
                      } else {
                        console.log('Table Logs créée avec succès.');

                        db.run(createTableQueryEntity, (err) => {
                          if (err) {
                            console.error('Erreur lors de la création de la table Entity :', err.message);
                          } else {
                            console.log('Table Entity créée avec succès.');

                            db.run(createTableQueryRequest, (err) => {
                              if (err) {
                                console.error('Erreur lors de la création de la table Request :', err.message);
                              } else {
                                console.log('Table Request créée avec succès.');


                                db.run(createTableQueryForm, (err) => {
                                  if (err) {
                                    console.error('Erreur lors de la création de la table Form :', err.message);
                                  } else {
                                    console.log('Table Form créée avec succès.');

                                    insertInitialData();
                                  }
                                });
                              }
                            });
                          }
                        });
                      }
                    });
                  }
                });
              }
            });
          }
        });
      }
    });
  });
}

function insertInitialData() {
  const insertQueryLogs = `
    INSERT INTO Logs (Titre, Description) VALUES
    ('Update 1.0', 'Rien ajouté'),
    ('Update 1.1', "Ajout du choix de l'avatar"),
    ('Update 2.0', "Ajout de l'ajout");
  `;

  const insertQueryEntity = `
    INSERT INTO Entity (Name, Licence, Image) VALUES
    
    ("Mark Evans", "Inazuma Eleven", "Mark Evans.png"),
    ("Nathan Swift", "Inazuma Eleven", "Nathan Swift.png"),  
    ("Jack Wallside", "Inazuma Eleven", "Jack Wallside.png"),    
    ("Jim Wraith", "Inazuma Eleven", "Jim Wraith.png"),
    ("Tod Ironside", "Inazuma Eleven", "Tod Ironside.png"),      
    ("Steve Grim", "Inazuma Eleven", "Steve Grim.png"),
    ("Timmy Saunders", "Inazuma Eleven", "Timmy Saunders.png"),  
    ("Sam Kincaid", "Inazuma Eleven", "Sam Kincaid.png"),        
    ("Maxwell Carson", "Inazuma Eleven", "Maxwell Carson.png"),  
    ("Axel Blaze", "Inazuma Eleven", "Axel Blaze.png"),
    ("Kevin Dragonfly", "Inazuma Eleven", "Kevin Dragonfly.png"),
    ("William Glass", "Inazuma Eleven", "William Glass.png"),    
    ("Bobby Shearer", "Inazuma Eleven", "Bobby Shearer.png"),    
    ("Jude Sharp", "Inazuma Eleven", "Jude Sharp.png"),
    ("Erik Eagle", "Inazuma Eleven", "Erik Eagle.png"),
    ("Shadow Cimmerian", "Inazuma Eleven", "Shadow Cimmerian.png"),
    ("Byron Love", "Inazuma Eleven", "Byron Love.png"),
    ("Shawn Froste", "Inazuma Eleven", "Shawn Froste.png"),
    ("Scotty Banyan", "Inazuma Eleven", "Scotty Banyan.png"),
    ("Suzette Hartland", "Inazuma Eleven", "Suzette Hartland.png"),
    ("Darren LaChance", "Inazuma Eleven", "Darren LaChance.png"),
    ("Hurley Kane", "Inazuma Eleven", "Hurley Kane.png"),
    ("Archer Hawkins", "Inazuma Eleven", "Archer Hawkins.png"),
    ("Thor Stoutberg", "Inazuma Eleven", "Thor Stoutberg.png"),
    ("Austin Hobbes", "Inazuma Eleven", "Austin Hobbes.png"),
    ("Aatrox", "League of legends", "Aatrox.png"),
    ("Ahri", "League of legends", "Ahri.png"),
    ("Akali", "League of legends", "Akali.png"),
    ("Akshan", "League of legends", "Akshan.png"),
    ("Alistar", "League of legends", "Alistar.png"),
    ("Amumu", "League of legends", "Amumu.png"),
    ("Anivia", "League of legends", "Anivia.png"),
    ("Annie", "League of legends", "Annie.png"),
    ("Aphelios", "League of legends", "Aphelios.png"),
    ("Ashe", "League of legends", "Ashe.png"),
    ("Aurelion Sol", "League of legends", "Aurelion Sol.png"),
    ("Azir", "League of legends", "Azir.png"),
    ("Bard", "League of legends", "Bard.png"),
    ("Bel'veth", "League of legends", "Bel'Veth.png"),
    ("Blitzcrank", "League of legends", "Blitzcrank.png"),
    ("Brand", "League of legends", "Brand.png"),
    ("Braum", "League of legends", "Braum.png"),
    ("Briar", "League of legends", "Briar.png"),
    ("Caitlyn", "League of legends", "Caitlyn.png"),
    ("Camille", "League of legends", "Camille.png"),
    ("Cassiopeia", "League of legends", "Cassiopeia.png"),
    ("Cho'Gath", "League of legends", "Cho'Gath.png"),
    ("Corki", "League of legends", "Corki.png"),
    ("Darius", "League of legends", "Darius.png"),
    ("Diana", "League of legends", "Diana.png"),
    ("Dr. Mundo", "League of legends", "Dr. Mundo.png"),
    ("Draven", "League of legends", "Draven.png"),
    ("Ekko", "League of legends", "Ekko.png"),
    ("Elise", "League of legends", "Elise.png"),
    ("Evelynn", "League of legends", "Evelynn.png"),
    ("Ezreal", "League of legends", "Ezreal.png"),
    ("Fiddlesticks", "League of legends", "Fiddlesticks.png"),
    ("Fiora", "League of legends", "Fiora.png"),
    ("Fizz", "League of legends", "Fizz.png"),
    ("Galio", "League of legends", "Galio.png"),
    ("Gangplank", "League of legends", "Gangplank.png"),
    ("Garen", "League of legends", "Garen.png"),
    ("Gnar", "League of legends", "Gnar.png"),
    ("Gragas", "League of legends", "Gragas.png"),
    ("Graves", "League of legends", "Graves.png"),
    ("Gwen", "League of legends", "Gwen.png"),
    ("Hecarim", "League of legends", "Hecarim.png"),
    ("Heimerdinger", "League of legends", "Heimerdinger.png"),
    ("Hwei", "League of legends", "Hwei.png"),
    ("Illaoi", "League of legends", "Illaoi.png"),
    ("Irelia", "League of legends", "Irelia.png"),
    ("Ivern", "League of legends", "Ivern.png"),
    ("Janna", "League of legends", "Janna.png"),
    ("Jarvan IV", "League of legends", "Jarvan IV.png"),
    ("Jax", "League of legends", "Jax.png"),
    ("Jayce", "League of legends", "Jayce.png"),
    ("Jhin", "League of legends", "Jhin.png"),
    ("Jinx", "League of legends", "Jinx.png"),
    ("K'santé", "League of legends", "K'santé.png"),
    ("Kai'sa", "League of legends", "Kai'sa.png"),
    ("Kalista", "League of legends", "Kalista.png"),
    ("Karma", "League of legends", "Karma.png"),
    ("Karthus", "League of legends", "Karthus.png"),
    ("Kassadin", "League of legends", "Kassadin.png"),
    ("Katarina", "League of legends", "Katarina.png"),
    ("Kayle", "League of legends", "Kayle.png"),
    ("Kayn", "League of legends", "Kayn.png"),
    ("Kennen", "League of legends", "Kennen.png"),
        
        
    ("Kha'Zix", "League of legends", "Kha'Zix.png"),
    ("Kindred", "League of legends", "Kindred.png"),
    ("Kled", "League of legends", "Kled.png"),
    ("Kog'Maw", "League of legends", "Kog'Maw.png"),
    ("Leblanc", "League of legends", "Leblanc.png"),
    ("Lee Sin", "League of legends", "Lee Sin.png"),
    ("Leona", "League of legends", "Leona.png"),
    ("Lillia", "League of legends", "Lillia.png"),
    ("Lissandra", "League of legends", "Lissandra.png"),
    ("Lucian", "League of legends", "Lucian.png"),
    ("Lulu", "League of legends", "Lulu.png"),
    ("Lux", "League of legends", "Lux.png"),
    ("Malphite", "League of legends", "Malphite.png"),
    ("Malzahar", "League of legends", "Malzahar.png"),
    ("Maokai", "League of legends", "Maokai.png"),
    ("Maître Yi", "League of legends", "Maître Yi.png"),
    ("Milio", "League of legends", "Milio.png"),
    ("Miss Fortune", "League of legends", "Miss Fortune.png"),
    ("Mordekaiser", "League of legends", "Mordekaiser.png"),
    ("Morgana", "League of legends", "Morgana.png"),
    ("Naafiri", "League of legends", "Naafiri.png"),
    ("Nami", "League of legends", "Nami.png"),
    ("Nasus", "League of legends", "Nasus.png"),
    ("Nautilus", "League of legends", "Nautilus.png"),
    ("Neeko", "League of legends", "Neeko.png"),
    ("Nidalee", "League of legends", "Nidalee.png"),
    ("Nilah", "League of legends", "Nilah.png"),
    ("Nocturne", "League of legends", "Nocturne.png"),
    ("Nunu et Willump", "League of legends", "Nunu et Willump.png"),
    ("Olaf", "League of legends", "Olaf.png"),
    ("Orianna", "League of legends", "Orianna.png"),
    ("Ornn", "League of legends", "Ornn.png"),
    ("Pantheon", "League of legends", "Pantheon.png"),
    ("Poppy", "League of legends", "Poppy.png"),
    ("Pyke", "League of legends", "Pyke.png"),
    ("Qiyana", "League of legends", "Qiyana.png"),
    ("Quinn", "League of legends", "Quinn.png"),
    ("Rakan", "League of legends", "Rakan.png"),
    ("Rammus", "League of legends", "Rammus.png"),
    ("Rek'Sai", "League of legends", "Rek'Sai.png"),
    ("Rell", "League of legends", "Rell.png"),
    ("Renata Glasc", "League of legends", "Renata Glasc.png"),
    ("Renekton", "League of legends", "Renekton.png"),
    ("Rengar", "League of legends", "Rengar.png"),
    ("Riven", "League of legends", "Riven.png"),
    ("Rumble", "League of legends", "Rumble.png"),
    ("Ryze", "League of legends", "Ryze.png"),
    ("Samira", "League of legends", "Samira.png"),
    ("Sejuani", "League of legends", "Sejuani.png"),
    ("Senna", "League of legends", "Senna.png"),
    ("Sett", "League of legends", "Sett.png"),
    ("Shaco", "League of legends", "Shaco.png"),
    ("Shen", "League of legends", "Shen.png"),
    ("Shyvana", "League of legends", "Shyvana.png"),
    ("Singed", "League of legends", "Singed.png"),
    ("Singed", "League of legends", "Singed.png"),
    ("Sion", "League of legends", "Sion.png"),
    ("Sivir", "League of legends", "Sivir.png"),
    ("Skarner", "League of legends", "Skarner.png"),
    ("Smolder", "League of legends", "Smolder.png"),
    ("Sona", "League of legends", "Sona.png"),
    ("Soraka", "League of legends", "Soraka.png"),
    ("Swain", "League of legends", "Swain.png"),
    ("Sylas", "League of legends", "Sylas.png"),
    ("Syndra", "League of legends", "Syndra.png"),
    ("Séraphine", "League of legends", "Séraphine.png"),
    ("Tahm Kench", "League of legends", "Tahm Kench.png"),
    ("Taliyah", "League of legends", "Taliyah.png"),
    ("Talon", "League of legends", "Talon.png"),
    ("Taric", "League of legends", "Taric.png"),
    ("Teemo", "League of legends", "Teemo.png"),
    ("Thresh", "League of legends", "Thresh.png"),
    ("Tristana", "League of legends", "Tristana.png"),
    ("Trundle", "League of legends", "Trundle.png"),
    ("Tryndamere", "League of legends", "Tryndamere.png"),
    ("Twisted Fate", "League of legends", "Twisted Fate.png"),
    ("Twitch", "League of legends", "Twitch.png"),
    ("Udyr", "League of legends", "Udyr.png"),
    ("Urgot", "League of legends", "Urgot.png"),
    ("Varus", "League of legends", "Varus.png"),
    ("Vayne", "League of legends", "Vayne.png"),
    ("Veigar", "League of legends", "Veigar.png"),
    ("Vel'Koz", "League of legends", "Vel'Koz.png"),
    ("Vex", "League of legends", "Vex.png"),
    ("Vi", "League of legends", "Vi.png"),
    ("Viego", "League of legends", "Viego.png"),
    ("Viktor", "League of legends", "Viktor.png"),
    ("Vladimir", "League of legends", "Vladimir.png"),
    ("Volibear", "League of legends", "Volibear.png"),
    ("Warwick", "League of legends", "Warwick.png"),
    ("Wukong", "League of legends", "Wukong.png"),
    ("Xayah", "League of legends", "Xayah.png"),
    ("Xerath", "League of legends", "Xerath.png"),
    ("Xin Zhao", "League of legends", "Xin Zhao.png"),
    ("Yasuo", "League of legends", "Yasuo.png"),
    ("Yone", "League of legends", "Yone.png"),
    ("Yorick", "League of legends", "Yorick.png"),
    ("Yuumi", "League of legends", "Yuumi.png"),
    ("Zac", "League of legends", "Zac.png"),
    ("Zed", "League of legends", "Zed.png"),
    ("Zeri", "League of legends", "Zeri.png"),
    ("Ziggs", "League of legends", "Ziggs.png"),
    ("Zilean", "League of legends", "Zilean.png"),
    ("Zoé", "League of legends", "Zoé.png"),
    ("Zyra", "League of legends", "Zyra.png"),


    ("Bulbizarre", "Pokémon 1G", "Bulbizarre.png"),
    ("Herbizarre", "Pokémon 1G", "Herbizarre.png"),
    ("Florizarre", "Pokémon 1G", "Florizarre.png"),
    ("Salamèche", "Pokémon 1G", "Salamèche.png"),
    ("Reptincel", "Pokémon 1G", "Reptincel.png"),
    ("Dracaufeu", "Pokémon 1G", "Dracaufeu.png"),
    ("Carapuce", "Pokémon 1G", "Carapuce.png"),
    ("Carabaffe", "Pokémon 1G", "Carabaffe.png"),
    ("Tortank", "Pokémon 1G", "Tortank.png"),
    ("Chenipan", "Pokémon 1G", "Chenipan.png"),
    ("Chrysacier", "Pokémon 1G", "Chrysacier.png"),
    ("Papilusion", "Pokémon 1G", "Papilusion.png"),
    ("Aspicot", "Pokémon 1G", "Aspicot.png"),
    ("Coconfort", "Pokémon 1G", "Coconfort.png"),
    ("Dardargnan", "Pokémon 1G", "Dardargnan.png"),
    ("Roucool", "Pokémon 1G", "Roucool.png"),
    ("Roucoups", "Pokémon 1G", "Roucoups.png"),
    ("Roucarnage", "Pokémon 1G", "Roucarnage.png"),
    ("Rattata", "Pokémon 1G", "Rattata.png"),
    ("Rattatac", "Pokémon 1G", "Rattatac.png"),
    ("Piafabec", "Pokémon 1G", "Piafabec.png"),
    ("Rapasdepic", "Pokémon 1G", "Rapasdepic.png"),
    ("Abo", "Pokémon 1G", "Abo.png"),
    ("Arbok", "Pokémon 1G", "Arbok.png"),
    ("Pikachu", "Pokémon 1G", "Pikachu.png"),
    ("Raichu", "Pokémon 1G", "Raichu.png"),
    ("Sabelette", "Pokémon 1G", "Sabelette.png"),
    ("Sablaireau", "Pokémon 1G", "Sablaireau.png"),
    ("Nidoran♀", "Pokémon 1G", "NidoranF.png"),
    ("Nidorina", "Pokémon 1G", "Nidorina.png"),
    ("Nidoqueen", "Pokémon 1G", "Nidoqueen.png"),
    ("Nidoran♂", "Pokémon 1G", "NidoranM.png"),
    ("Nidorino", "Pokémon 1G", "Nidorino.png"),
    ("Nidoking", "Pokémon 1G", "Nidoking.png"),
    ("Mélofée", "Pokémon 1G", "Mélofée.png"),
    ("Mélodelfe", "Pokémon 1G", "Mélodelfe.png"),
    ("Goupix", "Pokémon 1G", "Goupix.png"),
    ("Feunard", "Pokémon 1G", "Feunard.png"),
    ("Rondoudou", "Pokémon 1G", "Rondoudou.png"),
    ("Grodoudou", "Pokémon 1G", "Grodoudou.png"),
    ("Nosferapti", "Pokémon 1G", "Nosferapti.png"),
    ("Nosferalto", "Pokémon 1G", "Nosferalto.png"),
    ("Mystherbe", "Pokémon 1G", "Mystherbe.png"),
    ("Ortide", "Pokémon 1G", "Ortide.png"),
    ("Rafflesia", "Pokémon 1G", "Rafflesia.png"),
    ("Paras", "Pokémon 1G", "Paras.png"),
    ("Parasect", "Pokémon 1G", "Parasect.png"),
    ("Mimitoss", "Pokémon 1G", "Mimitoss.png"),
    ("Aéromite", "Pokémon 1G", "Aéromite.png"),
    ("Taupiqueur", "Pokémon 1G", "Taupiqueur.png"),
    ("Triopikeur", "Pokémon 1G", "Triopikeur.png"),
    ("Miaouss", "Pokémon 1G", "Miaouss.png"),
    ("Persian", "Pokémon 1G", "Persian.png"),
    ("Psykokwak", "Pokémon 1G", "Psykokwak.png"),
    ("Akwakwak", "Pokémon 1G", "Akwakwak.png"),
    ("Férosinge", "Pokémon 1G", "Férosinge.png"),
    ("Colossinge", "Pokémon 1G", "Colossinge.png"),
    ("Caninos", "Pokémon 1G", "Caninos.png"),
    ("Arcanin", "Pokémon 1G", "Arcanin.png"),
    ("Ptitard", "Pokémon 1G", "Ptitard.png"),
    ("Têtarte", "Pokémon 1G", "Têtarte.png"),
    ("Tartard", "Pokémon 1G", "Tartard.png"),
    ("Abra", "Pokémon 1G", "Abra.png"),
    ("Kadabra", "Pokémon 1G", "Kadabra.png"),
    ("Alakazam", "Pokémon 1G", "Alakazam.png"),
    ("Machoc", "Pokémon 1G", "Machoc.png"),
    ("Machopeur", "Pokémon 1G", "Machopeur.png"),
    ("Mackogneur", "Pokémon 1G", "Mackogneur.png"),
    ("Chétiflor", "Pokémon 1G", "Chétiflor.png"),
    ("Boustiflor", "Pokémon 1G", "Boustiflor.png"),
    ("Empiflor", "Pokémon 1G", "Empiflor.png"),
    ("Tentacool", "Pokémon 1G", "Tentacool.png"),
    ("Tentacruel", "Pokémon 1G", "Tentacruel.png"),
    ("Racaillou", "Pokémon 1G", "Racaillou.png"),
    ("Gravalanch", "Pokémon 1G", "Gravalanch.png"),
    ("Grolem", "Pokémon 1G", "Grolem.png"),
    ("Ponyta", "Pokémon 1G", "Ponyta.png"),
    ("Galopa", "Pokémon 1G", "Galopa.png"),
    ("Ramoloss", "Pokémon 1G", "Ramoloss.png"),
    ("Flagadoss", "Pokémon 1G", "Flagadoss.png"),
    ("Magnéti", "Pokémon 1G", "Magnéti.png"),
    ("Magnéton", "Pokémon 1G", "Magnéton.png"),
    ("Canarticho", "Pokémon 1G", "Canarticho.png"),
    ("Doduo", "Pokémon 1G", "Doduo.png"),
    ("Dodrio", "Pokémon 1G", "Dodrio.png"),
    ("Otaria", "Pokémon 1G", "Otaria.png"),
    ("Lamantine", "Pokémon 1G", "Lamantine.png"),
    ("Tadmorv", "Pokémon 1G", "Tadmorv.png"),
    ("Grotadmorv", "Pokémon 1G", "Grotadmorv.png"),
    ("Kokiyas", "Pokémon 1G", "Kokiyas.png"),
    ("Crustabri", "Pokémon 1G", "Crustabri.png"),
    ("Fantominus", "Pokémon 1G", "Fantominus.png"),
    ("Spectrum", "Pokémon 1G", "Spectrum.png"),
    ("Ectoplasma", "Pokémon 1G", "Ectoplasma.png"),
    ("Onix", "Pokémon 1G", "Onix.png"),
    ("Soporifik", "Pokémon 1G", "Soporifik.png"),
    ("Hypnomade", "Pokémon 1G", "Hypnomade.png"),
    ("Krabby", "Pokémon 1G", "Krabby.png"),
    ("Krabboss", "Pokémon 1G", "Krabboss.png"),
    ("Voltorbe", "Pokémon 1G", "Voltorbe.png"),
    ("Électrode", "Pokémon 1G", "Électrode.png"),
    ("Noeunoeuf", "Pokémon 1G", "Noeunoeuf.png"),
    ("Noadkoko", "Pokémon 1G", "Noadkoko.png"),
    ("Osselait", "Pokémon 1G", "Osselait.png"),
    ("Ossatueur", "Pokémon 1G", "Ossatueur.png"),
    ("Kicklee", "Pokémon 1G", "Kicklee.png"),
    ("Tygnon", "Pokémon 1G", "Tygnon.png"),
    ("Excelangue", "Pokémon 1G", "Excelangue.png"),
    ("Smogo", "Pokémon 1G", "Smogo.png"),
    ("Smogogo", "Pokémon 1G", "Smogogo.png"),
    ("Rhinocorne", "Pokémon 1G", "Rhinocorne.png"),
    ("Rhinoféros", "Pokémon 1G", "Rhinoféros.png"),
    ("Leveinard", "Pokémon 1G", "Leveinard.png"),
    ("Saquedeneu", "Pokémon 1G", "Saquedeneu.png"),
    ("Kangourex", "Pokémon 1G", "Kangourex.png"),
    ("Hypotrempe", "Pokémon 1G", "Hypotrempe.png"),
    ("Hypocéan", "Pokémon 1G", "Hypocéan.png"),
    ("Poissirène", "Pokémon 1G", "Poissirène.png"),
    ("Poissoroy", "Pokémon 1G", "Poissoroy.png"),
    ("Stari", "Pokémon 1G", "Stari.png"),
    ("Staross", "Pokémon 1G", "Staross.png"),
    ("M. Mime", "Pokémon 1G", "M. Mime.png"),
    ("Insécateur", "Pokémon 1G", "Insécateur.png"),
    ("Lippoutou", "Pokémon 1G", "Lippoutou.png"),
    ("Élektek", "Pokémon 1G", "Élektek.png"),
    ("Magmar", "Pokémon 1G", "Magmar.png"),
    ("Scarabrute", "Pokémon 1G", "Scarabrute.png"),
    ("Tauros", "Pokémon 1G", "Tauros.png"),
    ("Magicarpe", "Pokémon 1G", "Magicarpe.png"),
    ("Léviator", "Pokémon 1G", "Léviator.png"),
    ("Lokhlass", "Pokémon 1G", "Lokhlass.png"),
    ("Métamorph", "Pokémon 1G", "Métamorph.png"),
    ("Évoli", "Pokémon 1G", "Évoli.png"),
    ("Aquali", "Pokémon 1G", "Aquali.png"),
    ("Voltali", "Pokémon 1G", "Voltali.png"),
    ("Pyroli", "Pokémon 1G", "Pyroli.png"),
    ("Porygon", "Pokémon 1G", "Porygon.png"),
    ("Amonita", "Pokémon 1G", "Amonita.png"),
    ("Amonistar", "Pokémon 1G", "Amonistar.png"),
    ("Kabuto", "Pokémon 1G", "Kabuto.png"),
    ("Kabutops", "Pokémon 1G", "Kabutops.png"),
    ("Ptéra", "Pokémon 1G", "Ptéra.png"),
    ("Ronflex", "Pokémon 1G", "Ronflex.png"),
    ("Artikodin", "Pokémon 1G", "Artikodin.png"),
    ("Électhor", "Pokémon 1G", "Électhor.png"),
    ("Sulfura", "Pokémon 1G", "Sulfura.png"),
    ("Minidraco", "Pokémon 1G", "Minidraco.png"),
    ("Draco", "Pokémon 1G", "Draco.png"),
    ("Dracolosse", "Pokémon 1G", "Dracolosse.png"),
    ("Mewtwo", "Pokémon 1G", "Mewtwo.png"),
    ("Mew", "Pokémon 1G", "Mew.png"),



    
    ("1", "Test", "1.png"),
    ("2", "Test", "2.png")
    
    ;
  `;


  const insertPokemonEntity = `

    INSERT INTO Pokemon (Nom_FR, Nom_EN, Nom_JP, Generation, Rare, Type_1, Type_2, Cri) VALUES
    ('Bulbizarre.png', 'Bulbizarre', 'Bulbasaur', 'フシギダネ', 1, 'Commun', 'Grass', 'Poison', 'sons/pokemon/1.ogg'),
    ('Herbizarre.png', 'Herbizarre', 'Ivysaur', 'フシギソウ', 1, 'Commun', 'Grass', 'Poison', 'sons/pokemon/2.ogg'),  
    ('Florizarre.png', 'Florizarre', 'Venusaur', 'フシギバナ', 1, 'Commun', 'Grass', 'Poison', 'sons/pokemon/3.ogg'), 
    ('Salamèche.png', 'Salamèche', 'Charmander', 'ヒトカゲ', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/4.ogg'),     
    ('Reptincel.png', 'Reptincel', 'Charmeleon', 'リザード', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/5.ogg'),     
    ('Dracaufeu.png', 'Dracaufeu', 'Charizard', 'リザードン', 1, 'Commun', 'Fire', 'Flying', 'sons/pokemon/6.ogg'),   
    ('Carapuce.png', 'Carapuce', 'Squirtle', 'ゼニガメ', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/7.ogg'),        
    ('Carabaffe.png', 'Carabaffe', 'Wartortle', 'カメール', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/8.ogg'),     
    ('Tortank.png', 'Tortank', 'Blastoise', 'カメックス', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/9.ogg'),       
    ('Chenipan.png', 'Chenipan', 'Caterpie', 'キャタピー', 1, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/10.ogg'),       
    ('Chrysacier.png', 'Chrysacier', 'Metapod', 'トランセル', 1, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/11.ogg'),    
    ('Papilusion.png', 'Papilusion', 'Butterfree', 'バタフリー', 1, 'Commun', 'Bug', 'Flying', 'sons/pokemon/12.ogg'),
    ('Aspicot.png', 'Aspicot', 'Weedle', 'ビードル', 1, 'Commun', 'Bug', 'Poison', 'sons/pokemon/13.ogg'),
    ('Coconfort.png', 'Coconfort', 'Kakuna', 'コクーン', 1, 'Commun', 'Bug', 'Poison', 'sons/pokemon/14.ogg'),
    ('Dardargnan.png', 'Dardargnan', 'Beedrill', 'スピアー', 1, 'Commun', 'Bug', 'Poison', 'sons/pokemon/15.ogg'),
    ('Roucool.png', 'Roucool', 'Pidgey', 'ポッポ', 1, 'Commun', 'Normal', 'Flying', 'sons/pokemon/16.ogg'),
    ('Roucoups.png', 'Roucoups', 'Pidgeotto', 'ピジョン', 1, 'Commun', 'Normal', 'Flying', 'sons/pokemon/17.ogg'),
    ('Roucarnage.png', 'Roucarnage', 'Pidgeot', 'ピジョット', 1, 'Commun', 'Normal', 'Flying', 'sons/pokemon/18.ogg'),
    ('Rattata.png', 'Rattata', 'Rattata', 'コラッタ', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/19.ogg'),
    ('Rattatac.png', 'Rattatac', 'Raticate', 'ラッタ', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/20.ogg'),
    ('Piafabec.png', 'Piafabec', 'Spearow', 'オニスズメ', 1, 'Commun', 'Normal', 'Flying', 'sons/pokemon/21.ogg'),
    ('Rapasdepic.png', 'Rapasdepic', 'Fearow', 'オニドリル', 1, 'Commun', 'Normal', 'Flying', 'sons/pokemon/22.ogg'),
    ('Abo.png', 'Abo', 'Ekans', 'アーボ', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/23.ogg'),
    ('Arbok.png', 'Arbok', 'Arbok', 'アーボック', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/24.ogg'),
    ('Pikachu.png', 'Pikachu', 'Pikachu', 'ピカチュウ', 1, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/25.ogg'),
    ('Raichu.png', 'Raichu', 'Raichu', 'ライチュウ', 1, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/26.ogg'),
    ('Sabelette.png', 'Sabelette', 'Sandshrew', 'サンド', 1, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/27.ogg'),
    ('Sablaireau.png', 'Sablaireau', 'Sandslash', 'サンドパン', 1, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/28.ogg'),
    ('Nidoran♀.png', 'Nidoran♀', 'Nidoran♀', 'ニドラン♀', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/29.ogg'),
    ('Nidorina.png', 'Nidorina', 'Nidorina', 'ニドリーナ', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/30.ogg'),
    ('Nidoqueen.png', 'Nidoqueen', 'Nidoqueen', 'ニドクイン', 1, 'Commun', 'Poison', 'Ground', 'sons/pokemon/31.ogg'),
    ('Nidoran♂.png', 'Nidoran♂', 'Nidoran♂', 'ニドラン♂', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/32.ogg'),
    ('Nidorino.png', 'Nidorino', 'Nidorino', 'ニドリーノ', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/33.ogg'),
    ('Nidoking.png', 'Nidoking', 'Nidoking', 'ニドキング', 1, 'Commun', 'Poison', 'Ground', 'sons/pokemon/34.ogg'),
    ('Mélofée.png', 'Mélofée', 'Clefairy', 'ピッピ', 1, 'Commun', 'Fairy', 'Aucun', 'sons/pokemon/35.ogg'),
    ('Mélodelfe.png', 'Mélodelfe', 'Clefable', 'ピクシー', 1, 'Commun', 'Fairy', 'Aucun', 'sons/pokemon/36.ogg'),
    ('Goupix.png', 'Goupix', 'Vulpix', 'ロコン', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/37.ogg'),
    ('Feunard.png', 'Feunard', 'Ninetales', 'キュウコン', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/38.ogg'),
    ('Rondoudou.png', 'Rondoudou', 'Jigglypuff', 'プリン', 1, 'Commun', 'Normal', 'Fairy', 'sons/pokemon/39.ogg'),
    ('Grodoudou.png', 'Grodoudou', 'Wigglytuff', 'プクリン', 1, 'Commun', 'Normal', 'Fairy', 'sons/pokemon/40.ogg'),
    ('Nosferapti.png', 'Nosferapti', 'Zubat', 'ズバット', 1, 'Commun', 'Poison', 'Flying', 'sons/pokemon/41.ogg'),
    ('Nosferalto.png', 'Nosferalto', 'Golbat', 'ゴルバット', 1, 'Commun', 'Poison', 'Flying', 'sons/pokemon/42.ogg'),
    ('Mystherbe.png', 'Mystherbe', 'Oddish', 'ナゾノクサ', 1, 'Commun', 'Grass', 'Poison', 'sons/pokemon/43.ogg'),
    ('Ortide.png', 'Ortide', 'Gloom', 'クサイハナ', 1, 'Commun', 'Grass', 'Poison', 'sons/pokemon/44.ogg'),
    ('Rafflesia.png', 'Rafflesia', 'Vileplume', 'ラフレシア', 1, 'Commun', 'Grass', 'Poison', 'sons/pokemon/45.ogg'),
    ('Paras.png', 'Paras', 'Paras', 'パラス', 1, 'Commun', 'Bug', 'Grass', 'sons/pokemon/46.ogg'),
    ('Parasect.png', 'Parasect', 'Parasect', 'パラセクト', 1, 'Commun', 'Bug', 'Grass', 'sons/pokemon/47.ogg'),
    ('Mimitoss.png', 'Mimitoss', 'Venonat', 'コンパン', 1, 'Commun', 'Bug', 'Poison', 'sons/pokemon/48.ogg'),
    ('Aéromite.png', 'Aéromite', 'Venomoth', 'モルフォン', 1, 'Commun', 'Bug', 'Poison', 'sons/pokemon/49.ogg'),
    ('Taupiqueur.png', 'Taupiqueur', 'Diglett', 'ディグダ', 1, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/50.ogg'),
    ('Triopikeur.png', 'Triopikeur', 'Dugtrio', 'ダグトリオ', 1, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/51.ogg'),
    ('Miaouss.png', 'Miaouss', 'Meowth', 'ニャース', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/52.ogg'),
    ('Persian.png', 'Persian', 'Persian', 'ペルシアン', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/53.ogg'),
    ('Psykokwak.png', 'Psykokwak', 'Psyduck', 'コダック', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/54.ogg'),
    ('Akwakwak.png', 'Akwakwak', 'Golduck', 'ゴルダック', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/55.ogg'),
    ('Férosinge.png', 'Férosinge', 'Mankey', 'マンキー', 1, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/56.ogg'),
    ('Colossinge.png', 'Colossinge', 'Primeape', 'オコリザル', 1, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/57.ogg'),
    ('Caninos.png', 'Caninos', 'Growlithe', 'ガーディ', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/58.ogg'),
    ('Arcanin.png', 'Arcanin', 'Arcanine', 'ウインディ', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/59.ogg'),
    ('Ptitard.png', 'Ptitard', 'Poliwag', 'ニョロモ', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/60.ogg'),
    ('Têtarte.png', 'Têtarte', 'Poliwhirl', 'ニョロゾ', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/61.ogg'),
    ('Tartard.png', 'Tartard', 'Poliwrath', 'ニョロボン', 1, 'Commun', 'Water', 'Fighting', 'sons/pokemon/62.ogg'),
    ('Abra.png', 'Abra', 'Abra', 'ケーシィ', 1, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/63.ogg'),
    ('Kadabra.png', 'Kadabra', 'Kadabra', 'ユンゲラー', 1, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/64.ogg'),
    ('Alakazam.png', 'Alakazam', 'Alakazam', 'フーディン', 1, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/65.ogg'),
    ('Machoc.png', 'Machoc', 'Machop', 'ワンリキー', 1, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/66.ogg'),
    ('Machopeur.png', 'Machopeur', 'Machoke', 'ゴーリキー', 1, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/67.ogg'),
    ('Mackogneur.png', 'Mackogneur', 'Machamp', 'カイリキー', 1, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/68.ogg'),
    ('Chétiflor.png', 'Chétiflor', 'Bellsprout', 'マダツボミ', 1, 'Commun', 'Grass', 'Poison', 'sons/pokemon/69.ogg'),
    ('Boustiflor.png', 'Boustiflor', 'Weepinbell', 'ウツドン', 1, 'Commun', 'Grass', 'Poison', 'sons/pokemon/70.ogg'),
    ('Empiflor.png', 'Empiflor', 'Victreebel', 'ウツボット', 1, 'Commun', 'Grass', 'Poison', 'sons/pokemon/71.ogg'),
    ('Tentacool.png', 'Tentacool', 'Tentacool', 'メノクラゲ', 1, 'Commun', 'Water', 'Poison', 'sons/pokemon/72.ogg'),
    ('Tentacruel.png', 'Tentacruel', 'Tentacruel', 'ドククラゲ', 1, 'Commun', 'Water', 'Poison', 'sons/pokemon/73.ogg'),
    ('Racaillou.png', 'Racaillou', 'Geodude', 'イシツブテ', 1, 'Commun', 'Rock', 'Ground', 'sons/pokemon/74.ogg'),
    ('Gravalanch.png', 'Gravalanch', 'Graveler', 'ゴローン', 1, 'Commun', 'Rock', 'Ground', 'sons/pokemon/75.ogg'),
    ('Grolem.png', 'Grolem', 'Golem', 'ゴローニャ', 1, 'Commun', 'Rock', 'Ground', 'sons/pokemon/76.ogg'),
    ('Ponyta.png', 'Ponyta', 'Ponyta', 'ポニータ', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/77.ogg'),
    ('Galopa.png', 'Galopa', 'Rapidash', 'ギャロップ', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/78.ogg'),
    ('Ramoloss.png', 'Ramoloss', 'Slowpoke', 'ヤドン', 1, 'Commun', 'Water', 'Psychic', 'sons/pokemon/79.ogg'),
    ('Flagadoss.png', 'Flagadoss', 'Slowbro', 'ヤドラン', 1, 'Commun', 'Water', 'Psychic', 'sons/pokemon/80.ogg'),
    ('Magnéti.png', 'Magnéti', 'Magnemite', 'コイル', 1, 'Commun', 'Electric', 'Steel', 'sons/pokemon/81.ogg'),
    ('Magnéton.png', 'Magnéton', 'Magneton', 'レアコイル', 1, 'Commun', 'Electric', 'Steel', 'sons/pokemon/82.ogg'),
    ('Canarticho.png', 'Canarticho', "Farfetch'd", 'カモネギ', 1, 'Commun', 'Normal', 'Flying', 'sons/pokemon/83.ogg'),
    ('Doduo.png', 'Doduo', 'Doduo', 'ドードー', 1, 'Commun', 'Normal', 'Flying', 'sons/pokemon/84.ogg'),
    ('Dodrio.png', 'Dodrio', 'Dodrio', 'ドードリオ', 1, 'Commun', 'Normal', 'Flying', 'sons/pokemon/85.ogg'),
    ('Otaria.png', 'Otaria', 'Seel', 'パウワウ', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/86.ogg'),
    ('Lamantine.png', 'Lamantine', 'Dewgong', 'ジュゴン', 1, 'Commun', 'Water', 'Ice', 'sons/pokemon/87.ogg'),
    ('Tadmorv.png', 'Tadmorv', 'Grimer', 'ベトベター', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/88.ogg'),
    ('Grotadmorv.png', 'Grotadmorv', 'Muk', 'ベトベトン', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/89.ogg'),
    ('Kokiyas.png', 'Kokiyas', 'Shellder', 'シェルダー', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/90.ogg'),
    ('Crustabri.png', 'Crustabri', 'Cloyster', 'パルシェン', 1, 'Commun', 'Water', 'Ice', 'sons/pokemon/91.ogg'),
    ('Fantominus.png', 'Fantominus', 'Gastly', 'ゴース', 1, 'Commun', 'Ghost', 'Poison', 'sons/pokemon/92.ogg'),
    ('Spectrum.png', 'Spectrum', 'Haunter', 'ゴースト', 1, 'Commun', 'Ghost', 'Poison', 'sons/pokemon/93.ogg'),
    ('Ectoplasma.png', 'Ectoplasma', 'Gengar', 'ゲンガー', 1, 'Commun', 'Ghost', 'Poison', 'sons/pokemon/94.ogg'),
    ('Onix.png', 'Onix', 'Onix', 'イワーク', 1, 'Commun', 'Rock', 'Ground', 'sons/pokemon/95.ogg'),
    ('Soporifik.png', 'Soporifik', 'Drowzee', 'スリープ', 1, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/96.ogg'),
    ('Hypnomade.png', 'Hypnomade', 'Hypno', 'スリーパー', 1, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/97.ogg'),
    ('Krabby.png', 'Krabby', 'Krabby', 'クラブ', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/98.ogg'),
    ('Krabboss.png', 'Krabboss', 'Kingler', 'キングラー', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/99.ogg'),
    ('Voltorbe.png', 'Voltorbe', 'Voltorb', 'ビリリダマ', 1, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/100.ogg'),
    ('Électrode.png', 'Électrode', 'Electrode', 'マルマイン', 1, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/101.ogg'),
    ('Noeunoeuf.png', 'Noeunoeuf', 'Exeggcute', 'タマタマ', 1, 'Commun', 'Grass', 'Psychic', 'sons/pokemon/102.ogg'),
    ('Noadkoko.png', 'Noadkoko', 'Exeggutor', 'ナッシー', 1, 'Commun', 'Grass', 'Psychic', 'sons/pokemon/103.ogg'),
    ('Osselait.png', 'Osselait', 'Cubone', 'カラカラ', 1, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/104.ogg'),
    ('Ossatueur.png', 'Ossatueur', 'Marowak', 'ガラガラ', 1, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/105.ogg'),
    ('Kicklee.png', 'Kicklee', 'Hitmonlee', 'サワムラー', 1, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/106.ogg'),
    ('Tygnon.png', 'Tygnon', 'Hitmonchan', 'エビワラー', 1, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/107.ogg'),
    ('Excelangue.png', 'Excelangue', 'Lickitung', 'ベロリンガ', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/108.ogg'),
    ('Smogo.png', 'Smogo', 'Koffing', 'ドガース', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/109.ogg'),
    ('Smogogo.png', 'Smogogo', 'Weezing', 'マタドガス', 1, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/110.ogg'),
    ('Rhinocorne.png', 'Rhinocorne', 'Rhyhorn', 'サイホーン', 1, 'Commun', 'Ground', 'Rock', 'sons/pokemon/111.ogg'),
    ('Rhinoféros.png', 'Rhinoféros', 'Rhydon', 'サイドン', 1, 'Commun', 'Ground', 'Rock', 'sons/pokemon/112.ogg'),
    ('Leveinard.png', 'Leveinard', 'Chansey', 'ラッキー', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/113.ogg'),
    ('Saquedeneu.png', 'Saquedeneu', 'Tangela', 'モンジャラ', 1, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/114.ogg'),
    ('Kangourex.png', 'Kangourex', 'Kangaskhan', 'ガルーラ', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/115.ogg'),
    ('Hypotrempe.png', 'Hypotrempe', 'Horsea', 'タッツー', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/116.ogg'),
    ('Hypocéan.png', 'Hypocéan', 'Seadra', 'シードラ', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/117.ogg'),
    ('Poissirène.png', 'Poissirène', 'Goldeen', 'トサキント', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/118.ogg'),
    ('Poissoroy.png', 'Poissoroy', 'Seaking', 'アズマオウ', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/119.ogg'),
    ('Stari.png', 'Stari', 'Staryu', 'ヒトデマン', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/120.ogg'),
    ('Staross.png', 'Staross', 'Starmie', 'スターミー', 1, 'Commun', 'Water', 'Psychic', 'sons/pokemon/121.ogg'),
    ('M. Mime.png', 'M. Mime', 'Mr. Mime', 'バリヤード', 1, 'Commun', 'Psychic', 'Fairy', 'sons/pokemon/122.ogg'),
    ('Insécateur.png', 'Insécateur', 'Scyther', 'ストライク', 1, 'Commun', 'Bug', 'Flying', 'sons/pokemon/123.ogg'),
    ('Lippoutou.png', 'Lippoutou', 'Jynx', 'ルージュラ', 1, 'Commun', 'Ice', 'Psychic', 'sons/pokemon/124.ogg'),
    ('Élektek.png', 'Élektek', 'Electabuzz', 'エレブー', 1, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/125.ogg'),
    ('Magmar.png', 'Magmar', 'Magmar', 'ブーバー', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/126.ogg'),
    ('Scarabrute.png', 'Scarabrute', 'Pinsir', 'カイロス', 1, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/127.ogg'),
    ('Tauros.png', 'Tauros', 'Tauros', 'ケンタロス', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/128.ogg'),
    ('Magicarpe.png', 'Magicarpe', 'Magikarp', 'コイキング', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/129.ogg'),
    ('Léviator.png', 'Léviator', 'Gyarados', 'ギャラドス', 1, 'Commun', 'Water', 'Flying', 'sons/pokemon/130.ogg'),
    ('Lokhlass.png', 'Lokhlass', 'Lapras', 'ラプラス', 1, 'Commun', 'Water', 'Ice', 'sons/pokemon/131.ogg'),
    ('Métamorph.png', 'Métamorph', 'Ditto', 'メタモン', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/132.ogg'),
    ('Évoli.png', 'Évoli', 'Eevee', 'イーブイ', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/133.ogg'),
    ('Aquali.png', 'Aquali', 'Vaporeon', 'シャワーズ', 1, 'Commun', 'Water', 'Aucun', 'sons/pokemon/134.ogg'),
    ('Voltali.png', 'Voltali', 'Jolteon', 'サンダース', 1, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/135.ogg'),
    ('Pyroli.png', 'Pyroli', 'Flareon', 'ブースター', 1, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/136.ogg'),
    ('Porygon.png', 'Porygon', 'Porygon', 'ポリゴン', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/137.ogg'),
    ('Amonita.png', 'Amonita', 'Omanyte', 'オムナイト', 1, 'Commun', 'Rock', 'Water', 'sons/pokemon/138.ogg'),
    ('Amonistar.png', 'Amonistar', 'Omastar', 'オムスター', 1, 'Commun', 'Rock', 'Water', 'sons/pokemon/139.ogg'),
    ('Kabuto.png', 'Kabuto', 'Kabuto', 'カブト', 1, 'Commun', 'Rock', 'Water', 'sons/pokemon/140.ogg'),
    ('Kabutops.png', 'Kabutops', 'Kabutops', 'カブトプス', 1, 'Commun', 'Rock', 'Water', 'sons/pokemon/141.ogg'),
    ('Ptéra.png', 'Ptéra', 'Aerodactyl', 'プテラ', 1, 'Commun', 'Rock', 'Flying', 'sons/pokemon/142.ogg'),
    ('Ronflex.png', 'Ronflex', 'Snorlax', 'カビゴン', 1, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/143.ogg'),
    ('Artikodin.png', 'Artikodin', 'Articuno', 'フリーザー', 1, 'Commun', 'Ice', 'Flying', 'sons/pokemon/144.ogg'),
    ('Électhor.png', 'Électhor', 'Zapdos', 'サンダー', 1, 'Commun', 'Electric', 'Flying', 'sons/pokemon/145.ogg'),
    ('Sulfura.png', 'Sulfura', 'Moltres', 'ファイヤー', 1, 'Commun', 'Fire', 'Flying', 'sons/pokemon/146.ogg'),
    ('Minidraco.png', 'Minidraco', 'Dratini', 'ミニリュウ', 1, 'Commun', 'Dragon', 'Aucun', 'sons/pokemon/147.ogg'),
    ('Draco.png', 'Draco', 'Dragonair', 'ハクリュー', 1, 'Commun', 'Dragon', 'Aucun', 'sons/pokemon/148.ogg'),
    ('Dracolosse.png', 'Dracolosse', 'Dragonite', 'カイリュー', 1, 'Commun', 'Dragon', 'Flying', 'sons/pokemon/149.ogg'),
    ('Mewtwo.png', 'Mewtwo', 'Mewtwo', 'ミュウツー', 1, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/150.ogg'),
    ('Mew.png', 'Mew', 'Mew', 'ミュウ', 1, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/151.ogg'),
    ('Germignon.png', 'Germignon', 'Chikorita', 'チコリータ', 2, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/152.ogg'),
    ('Macronium.png', 'Macronium', 'Bayleef', 'ベイリーフ', 2, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/153.ogg'),
    ('Méganium.png', 'Méganium', 'Meganium', 'メガニウム', 2, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/154.ogg'),
    ('Héricendre.png', 'Héricendre', 'Cyndaquil', 'ヒノアラシ', 2, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/155.ogg'),
    ('Feurisson.png', 'Feurisson', 'Quilava', 'マグマラシ', 2, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/156.ogg'),
    ('Typhlosion.png', 'Typhlosion', 'Typhlosion', 'バクフーン', 2, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/157.ogg'),
    ('Kaiminus.png', 'Kaiminus', 'Totodile', 'ワニノコ', 2, 'Commun', 'Water', 'Aucun', 'sons/pokemon/158.ogg'),
    ('Crocrodil.png', 'Crocrodil', 'Croconaw', 'アリゲイツ', 2, 'Commun', 'Water', 'Aucun', 'sons/pokemon/159.ogg'),
    ('Aligatueur.png', 'Aligatueur', 'Feraligatr', 'オーダイル', 2, 'Commun', 'Water', 'Aucun', 'sons/pokemon/160.ogg'),
    ('Fouinette.png', 'Fouinette', 'Sentret', 'オタチ', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/161.ogg'),
    ('Fouinar.png', 'Fouinar', 'Furret', 'オオタチ', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/162.ogg'),
    ('Hoothoot.png', 'Hoothoot', 'Hoothoot', 'ホーホー', 2, 'Commun', 'Normal', 'Flying', 'sons/pokemon/163.ogg'),
    ('Noarfang.png', 'Noarfang', 'Noctowl', 'ヨルノズク', 2, 'Commun', 'Normal', 'Flying', 'sons/pokemon/164.ogg'),
    ('Coxy.png', 'Coxy', 'Ledyba', 'レディバ', 2, 'Commun', 'Bug', 'Flying', 'sons/pokemon/165.ogg'),
    ('Coxyclaque.png', 'Coxyclaque', 'Ledian', 'レディアン', 2, 'Commun', 'Bug', 'Flying', 'sons/pokemon/166.ogg'),
    ('Mimigal.png', 'Mimigal', 'Spinarak', 'イトマル', 2, 'Commun', 'Bug', 'Poison', 'sons/pokemon/167.ogg'),
    ('Migalos.png', 'Migalos', 'Ariados', 'アリアドス', 2, 'Commun', 'Bug', 'Poison', 'sons/pokemon/168.ogg'),
    ('Nostenfer.png', 'Nostenfer', 'Crobat', 'クロバット', 2, 'Commun', 'Poison', 'Flying', 'sons/pokemon/169.ogg'),
    ('Loupio.png', 'Loupio', 'Chinchou', 'チョンチー', 2, 'Commun', 'Water', 'Electric', 'sons/pokemon/170.ogg'),
    ('Lanturn.png', 'Lanturn', 'Lanturn', 'ランターン', 2, 'Commun', 'Water', 'Electric', 'sons/pokemon/171.ogg'),
    ('Pichu.png', 'Pichu', 'Pichu', 'ピチュー', 2, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/172.ogg'),
    ('Mélo.png', 'Mélo', 'Cleffa', 'ピィ', 2, 'Commun', 'Fairy', 'Aucun', 'sons/pokemon/173.ogg'),
    ('Toudoudou.png', 'Toudoudou', 'Igglybuff', 'ププリン', 2, 'Commun', 'Normal', 'Fairy', 'sons/pokemon/174.ogg'),
    ('Togepi.png', 'Togepi', 'Togepi', 'トゲピー', 2, 'Commun', 'Fairy', 'Aucun', 'sons/pokemon/175.ogg'),
    ('Togetic.png', 'Togetic', 'Togetic', 'トゲチック', 2, 'Commun', 'Fairy', 'Flying', 'sons/pokemon/176.ogg'),
    ('Natu.png', 'Natu', 'Natu', 'ネイティ', 2, 'Commun', 'Psychic', 'Flying', 'sons/pokemon/177.ogg'),
    ('Xatu.png', 'Xatu', 'Xatu', 'ネイティオ', 2, 'Commun', 'Psychic', 'Flying', 'sons/pokemon/178.ogg'),
    ('Wattouat.png', 'Wattouat', 'Mareep', 'メリープ', 2, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/179.ogg'),
    ('Lainergie.png', 'Lainergie', 'Flaaffy', 'モココ', 2, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/180.ogg'),
    ('Pharamp.png', 'Pharamp', 'Ampharos', 'デンリュウ', 2, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/181.ogg'),
    ('Joliflor.png', 'Joliflor', 'Bellossom', 'キレイハナ', 2, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/182.ogg'),
    ('Marill.png', 'Marill', 'Marill', 'マリル', 2, 'Commun', 'Water', 'Fairy', 'sons/pokemon/183.ogg'),
    ('Azumarill.png', 'Azumarill', 'Azumarill', 'マリルリ', 2, 'Commun', 'Water', 'Fairy', 'sons/pokemon/184.ogg'),
    ('Simularbre.png', 'Simularbre', 'Sudowoodo', 'ウソッキー', 2, 'Commun', 'Rock', 'Aucun', 'sons/pokemon/185.ogg'),
    ('Tarpaud.png', 'Tarpaud', 'Politoed', 'ニョロトノ', 2, 'Commun', 'Water', 'Aucun', 'sons/pokemon/186.ogg'),
    ('Granivol.png', 'Granivol', 'Hoppip', 'ハネッコ', 2, 'Commun', 'Grass', 'Flying', 'sons/pokemon/187.ogg'),
    ('Floravol.png', 'Floravol', 'Skiploom', 'ポポッコ', 2, 'Commun', 'Grass', 'Flying', 'sons/pokemon/188.ogg'),
    ('Cotovol.png', 'Cotovol', 'Jumpluff', 'ワタッコ', 2, 'Commun', 'Grass', 'Flying', 'sons/pokemon/189.ogg'),
    ('Capumain.png', 'Capumain', 'Aipom', 'エイパム', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/190.ogg'),
    ('Tournegrin.png', 'Tournegrin', 'Sunkern', 'ヒマナッツ', 2, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/191.ogg'),
    ('Héliatronc.png', 'Héliatronc', 'Sunflora', 'キマワリ', 2, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/192.ogg'),
    ('Yanma.png', 'Yanma', 'Yanma', 'ヤンヤンマ', 2, 'Commun', 'Bug', 'Flying', 'sons/pokemon/193.ogg'),
    ('Axoloto.png', 'Axoloto', 'Wooper', 'ウパー', 2, 'Commun', 'Water', 'Ground', 'sons/pokemon/194.ogg'),
    ('Maraiste.png', 'Maraiste', 'Quagsire', 'ヌオー', 2, 'Commun', 'Water', 'Ground', 'sons/pokemon/195.ogg'),
    ('Mentali.png', 'Mentali', 'Espeon', 'エーフィ', 2, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/196.ogg'),
    ('Noctali.png', 'Noctali', 'Umbreon', 'ブラッキー', 2, 'Commun', 'Dark', 'Aucun', 'sons/pokemon/197.ogg'),
    ('Cornèbre.png', 'Cornèbre', 'Murkrow', 'ヤミカラス', 2, 'Commun', 'Dark', 'Flying', 'sons/pokemon/198.ogg'),
    ('Roigada.png', 'Roigada', 'Slowking', 'ヤドキング', 2, 'Commun', 'Water', 'Psychic', 'sons/pokemon/199.ogg'),
    ('Feuforêve.png', 'Feuforêve', 'Misdreavus', 'ムウマ', 2, 'Commun', 'Ghost', 'Aucun', 'sons/pokemon/200.ogg'),
    ('Zarbi.png', 'Zarbi', 'Unown', 'アンノーン', 2, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/201.ogg'),
    ('Qulbutoké.png', 'Qulbutoké', 'Wobbuffet', 'ソーナンス', 2, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/202.ogg'),
    ('Girafarig.png', 'Girafarig', 'Girafarig', 'キリンリキ', 2, 'Commun', 'Normal', 'Psychic', 'sons/pokemon/203.ogg'),
    ('Pomdepik.png', 'Pomdepik', 'Pineco', 'クヌギダマ', 2, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/204.ogg'),
    ('Foretress.png', 'Foretress', 'Forretress', 'フォレトス', 2, 'Commun', 'Bug', 'Steel', 'sons/pokemon/205.ogg'),
    ('Insolourdo.png', 'Insolourdo', 'Dunsparce', 'ノコッチ', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/206.ogg'),
    ('Scorplane.png', 'Scorplane', 'Gligar', 'グライガー', 2, 'Commun', 'Ground', 'Flying', 'sons/pokemon/207.ogg'),
    ('Steelix.png', 'Steelix', 'Steelix', 'ハガネール', 2, 'Commun', 'Steel', 'Ground', 'sons/pokemon/208.ogg'),
    ('Snubbull.png', 'Snubbull', 'Snubbull', 'ブルー', 2, 'Commun', 'Fairy', 'Aucun', 'sons/pokemon/209.ogg'),
    ('Granbull.png', 'Granbull', 'Granbull', 'グランブル', 2, 'Commun', 'Fairy', 'Aucun', 'sons/pokemon/210.ogg'),
    ('Qwilfish.png', 'Qwilfish', 'Qwilfish', 'ハリーセン', 2, 'Commun', 'Water', 'Poison', 'sons/pokemon/211.ogg'),
    ('Cizayox.png', 'Cizayox', 'Scizor', 'ハッサム', 2, 'Commun', 'Bug', 'Steel', 'sons/pokemon/212.ogg'),
    ('Caratroc.png', 'Caratroc', 'Shuckle', 'ツボツボ', 2, 'Commun', 'Bug', 'Rock', 'sons/pokemon/213.ogg'),
    ('Scarhino.png', 'Scarhino', 'Heracross', 'ヘラクロス', 2, 'Commun', 'Bug', 'Fighting', 'sons/pokemon/214.ogg'),
    ('Farfuret.png', 'Farfuret', 'Sneasel', 'ニューラ', 2, 'Commun', 'Dark', 'Ice', 'sons/pokemon/215.ogg'),
    ('Teddiursa.png', 'Teddiursa', 'Teddiursa', 'ヒメグマ', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/216.ogg'),
    ('Ursaring.png', 'Ursaring', 'Ursaring', 'リングマ', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/217.ogg'),
    ('Limagma.png', 'Limagma', 'Slugma', 'マグマッグ', 2, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/218.ogg'),
    ('Volcaropod.png', 'Volcaropod', 'Magcargo', 'マグカルゴ', 2, 'Commun', 'Fire', 'Rock', 'sons/pokemon/219.ogg'),
    ('Marcacrin.png', 'Marcacrin', 'Swinub', 'ウリムー', 2, 'Commun', 'Ice', 'Ground', 'sons/pokemon/220.ogg'),
    ('Cochignon.png', 'Cochignon', 'Piloswine', 'イノムー', 2, 'Commun', 'Ice', 'Ground', 'sons/pokemon/221.ogg'),
    ('Corayon.png', 'Corayon', 'Corsola', 'サニーゴ', 2, 'Commun', 'Water', 'Rock', 'sons/pokemon/222.ogg'),
    ('Rémoraid.png', 'Rémoraid', 'Remoraid', 'テッポウオ', 2, 'Commun', 'Water', 'Aucun', 'sons/pokemon/223.ogg'),
    ('Octillery.png', 'Octillery', 'Octillery', 'オクタン', 2, 'Commun', 'Water', 'Aucun', 'sons/pokemon/224.ogg'),
    ('Cadoizo.png', 'Cadoizo', 'Delibird', 'デリバード', 2, 'Commun', 'Ice', 'Flying', 'sons/pokemon/225.ogg'),
    ('Démanta.png', 'Démanta', 'Mantine', 'マンタイン', 2, 'Commun', 'Water', 'Flying', 'sons/pokemon/226.ogg'),
    ('Airmure.png', 'Airmure', 'Skarmory', 'エアームド', 2, 'Commun', 'Steel', 'Flying', 'sons/pokemon/227.ogg'),
    ('Malosse.png', 'Malosse', 'Houndour', 'デルビル', 2, 'Commun', 'Dark', 'Fire', 'sons/pokemon/228.ogg'),
    ('Démolosse.png', 'Démolosse', 'Houndoom', 'ヘルガー', 2, 'Commun', 'Dark', 'Fire', 'sons/pokemon/229.ogg'),
    ('Hyporoi.png', 'Hyporoi', 'Kingdra', 'キングドラ', 2, 'Commun', 'Water', 'Dragon', 'sons/pokemon/230.ogg'),
    ('Phanpy.png', 'Phanpy', 'Phanpy', 'ゴマゾウ', 2, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/231.ogg'),
    ('Donphan.png', 'Donphan', 'Donphan', 'ドンファン', 2, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/232.ogg'),
    ('Porygon2.png', 'Porygon2', 'Porygon2', 'ポリゴン２', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/233.ogg'),
    ('Cerfrousse.png', 'Cerfrousse', 'Stantler', 'オドシシ', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/234.ogg'),
    ('Queulorior.png', 'Queulorior', 'Smeargle', 'ドーブル', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/235.ogg'),
    ('Debugant.png', 'Debugant', 'Tyrogue', 'バルキー', 2, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/236.ogg'),
    ('Kapoera.png', 'Kapoera', 'Hitmontop', 'カポエラー', 2, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/237.ogg'),
    ('Lippouti.png', 'Lippouti', 'Smoochum', 'ムチュール', 2, 'Commun', 'Ice', 'Psychic', 'sons/pokemon/238.ogg'),
    ('Élekid.png', 'Élekid', 'Elekid', 'エレキッド', 2, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/239.ogg'),
    ('Magby.png', 'Magby', 'Magby', 'ブビィ', 2, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/240.ogg'),
    ('Écrémeuh.png', 'Écrémeuh', 'Miltank', 'ミルタンク', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/241.ogg'),
    ('Leuphorie.png', 'Leuphorie', 'Blissey', 'ハピナス', 2, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/242.ogg'),
    ('Raikou.png', 'Raikou', 'Raikou', 'ライコウ', 2, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/243.ogg'),
    ('Entei.png', 'Entei', 'Entei', 'エンテイ', 2, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/244.ogg'),
    ('Suicune.png', 'Suicune', 'Suicune', 'スイクン', 2, 'Commun', 'Water', 'Aucun', 'sons/pokemon/245.ogg'),
    ('Embrylex.png', 'Embrylex', 'Larvitar', 'ヨーギラス', 2, 'Commun', 'Rock', 'Ground', 'sons/pokemon/246.ogg'),
    ('Ymphect.png', 'Ymphect', 'Pupitar', 'サナギラス', 2, 'Commun', 'Rock', 'Ground', 'sons/pokemon/247.ogg'),
    ('Tyranocif.png', 'Tyranocif', 'Tyranitar', 'バンギラス', 2, 'Commun', 'Rock', 'Dark', 'sons/pokemon/248.ogg'),
    ('Lugia.png', 'Lugia', 'Lugia', 'ルギア', 2, 'Commun', 'Psychic', 'Flying', 'sons/pokemon/249.ogg'),
    ('Ho-Oh.png', 'Ho-Oh', 'Ho-Oh', 'ホウオウ', 2, 'Commun', 'Fire', 'Flying', 'sons/pokemon/250.ogg'),
    ('Celebi.png', 'Celebi', 'Celebi', 'セレビィ', 2, 'Commun', 'Psychic', 'Grass', 'sons/pokemon/251.ogg'),
    ('Arcko.png', 'Arcko', 'Treecko', 'キモリ', 3, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/252.ogg'),
    ('Massko.png', 'Massko', 'Grovyle', 'ジュプトル', 3, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/253.ogg'),
    ('Jungko.png', 'Jungko', 'Sceptile', 'ジュカイン', 3, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/254.ogg'),
    ('Poussifeu.png', 'Poussifeu', 'Torchic', 'アチャモ', 3, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/255.ogg'),
    ('Galifeu.png', 'Galifeu', 'Combusken', 'ワカシャモ', 3, 'Commun', 'Fire', 'Fighting', 'sons/pokemon/256.ogg'),
    ('Braségali.png', 'Braségali', 'Blaziken', 'バシャーモ', 3, 'Commun', 'Fire', 'Fighting', 'sons/pokemon/257.ogg'),
    ('Gobou.png', 'Gobou', 'Mudkip', 'ミズゴロウ', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/258.ogg'),
    ('Flobio.png', 'Flobio', 'Marshtomp', 'ヌマクロー', 3, 'Commun', 'Water', 'Ground', 'sons/pokemon/259.ogg'),
    ('Laggron.png', 'Laggron', 'Swampert', 'ラグラージ', 3, 'Commun', 'Water', 'Ground', 'sons/pokemon/260.ogg'),
    ('Medhyèna.png', 'Medhyèna', 'Poochyena', 'ポチエナ', 3, 'Commun', 'Dark', 'Aucun', 'sons/pokemon/261.ogg'),
    ('Grahyèna.png', 'Grahyèna', 'Mightyena', 'グラエナ', 3, 'Commun', 'Dark', 'Aucun', 'sons/pokemon/262.ogg'),
    ('Zigzaton.png', 'Zigzaton', 'Zigzagoon', 'ジグザグマ', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/263.ogg'),
    ('Linéon.png', 'Linéon', 'Linoone', 'マッスグマ', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/264.ogg'),
    ('Chenipotte.png', 'Chenipotte', 'Wurmple', 'ケムッソ', 3, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/265.ogg'),
    ('Armulys.png', 'Armulys', 'Silcoon', 'カラサリス', 3, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/266.ogg'),
    ('Charmillon.png', 'Charmillon', 'Beautifly', 'アゲハント', 3, 'Commun', 'Bug', 'Flying', 'sons/pokemon/267.ogg'),
    ('Blindalys.png', 'Blindalys', 'Cascoon', 'マユルド', 3, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/268.ogg'),
    ('Papinox.png', 'Papinox', 'Dustox', 'ドクケイル', 3, 'Commun', 'Bug', 'Poison', 'sons/pokemon/269.ogg'),
    ('Nénupiot.png', 'Nénupiot', 'Lotad', 'ハスボー', 3, 'Commun', 'Water', 'Grass', 'sons/pokemon/270.ogg'),
    ('Lombre.png', 'Lombre', 'Lombre', 'ハスブレロ', 3, 'Commun', 'Water', 'Grass', 'sons/pokemon/271.ogg'),
    ('Ludicolo.png', 'Ludicolo', 'Ludicolo', 'ルンパッパ', 3, 'Commun', 'Water', 'Grass', 'sons/pokemon/272.ogg'),
    ('Grainipiot.png', 'Grainipiot', 'Seedot', 'タネボー', 3, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/273.ogg'),
    ('Pifeuil.png', 'Pifeuil', 'Nuzleaf', 'コノハナ', 3, 'Commun', 'Grass', 'Dark', 'sons/pokemon/274.ogg'),
    ('Tengalice.png', 'Tengalice', 'Shiftry', 'ダーテング', 3, 'Commun', 'Grass', 'Dark', 'sons/pokemon/275.ogg'),
    ('Nirondelle.png', 'Nirondelle', 'Taillow', 'スバメ', 3, 'Commun', 'Normal', 'Flying', 'sons/pokemon/276.ogg'),
    ('Hélédelle.png', 'Hélédelle', 'Swellow', 'オオスバメ', 3, 'Commun', 'Normal', 'Flying', 'sons/pokemon/277.ogg'),
    ('Goélise.png', 'Goélise', 'Wingull', 'キャモメ', 3, 'Commun', 'Water', 'Flying', 'sons/pokemon/278.ogg'),
    ('Bekipan.png', 'Bekipan', 'Pelipper', 'ペリッパー', 3, 'Commun', 'Water', 'Flying', 'sons/pokemon/279.ogg'),
    ('Tarsal.png', 'Tarsal', 'Ralts', 'ラルトス', 3, 'Commun', 'Psychic', 'Fairy', 'sons/pokemon/280.ogg'),
    ('Kirlia.png', 'Kirlia', 'Kirlia', 'キルリア', 3, 'Commun', 'Psychic', 'Fairy', 'sons/pokemon/281.ogg'),
    ('Gardevoir.png', 'Gardevoir', 'Gardevoir', 'サーナイト', 3, 'Commun', 'Psychic', 'Fairy', 'sons/pokemon/282.ogg'),
    ('Arakdo.png', 'Arakdo', 'Surskit', 'アメタマ', 3, 'Commun', 'Bug', 'Water', 'sons/pokemon/283.ogg'),
    ('Maskadra.png', 'Maskadra', 'Masquerain', 'アメモース', 3, 'Commun', 'Bug', 'Flying', 'sons/pokemon/284.ogg'),
    ('Balignon.png', 'Balignon', 'Shroomish', 'キノココ', 3, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/285.ogg'),
    ('Chapignon.png', 'Chapignon', 'Breloom', 'キノガッサ', 3, 'Commun', 'Grass', 'Fighting', 'sons/pokemon/286.ogg'),
    ('Parecool.png', 'Parecool', 'Slakoth', 'ナマケロ', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/287.ogg'),
    ('Vigoroth.png', 'Vigoroth', 'Vigoroth', 'ヤルキモノ', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/288.ogg'),
    ('Monaflèmit.png', 'Monaflèmit', 'Slaking', 'ケッキング', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/289.ogg'),
    ('Ningale.png', 'Ningale', 'Nincada', 'ツチニン', 3, 'Commun', 'Bug', 'Ground', 'sons/pokemon/290.ogg'),
    ('Ninjask.png', 'Ninjask', 'Ninjask', 'テッカニン', 3, 'Commun', 'Bug', 'Flying', 'sons/pokemon/291.ogg'),
    ('Munja.png', 'Munja', 'Shedinja', 'ヌケニン', 3, 'Commun', 'Bug', 'Ghost', 'sons/pokemon/292.ogg'),
    ('Chuchmur.png', 'Chuchmur', 'Whismur', 'ゴニョニョ', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/293.ogg'),
    ('Ramboum.png', 'Ramboum', 'Loudred', 'ドゴーム', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/294.ogg'),
    ('Brouhabam.png', 'Brouhabam', 'Exploud', 'バクオング', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/295.ogg'),
    ('Makuhita.png', 'Makuhita', 'Makuhita', 'マクノシタ', 3, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/296.ogg'),
    ('Hariyama.png', 'Hariyama', 'Hariyama', 'ハリテヤマ', 3, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/297.ogg'),
    ('Azurill.png', 'Azurill', 'Azurill', 'ルリリ', 3, 'Commun', 'Normal', 'Fairy', 'sons/pokemon/298.ogg'),
    ('Tarinor.png', 'Tarinor', 'Nosepass', 'ノズパス', 3, 'Commun', 'Rock', 'Aucun', 'sons/pokemon/299.ogg'),
    ('Skitty.png', 'Skitty', 'Skitty', 'エネコ', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/300.ogg'),
    ('Delcatty.png', 'Delcatty', 'Delcatty', 'エネコロロ', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/301.ogg'),
    ('Ténéfix.png', 'Ténéfix', 'Sableye', 'ヤミラミ', 3, 'Commun', 'Dark', 'Ghost', 'sons/pokemon/302.ogg'),
    ('Mysdibule.png', 'Mysdibule', 'Mawile', 'クチート', 3, 'Commun', 'Steel', 'Fairy', 'sons/pokemon/303.ogg'),
    ('Galekid.png', 'Galekid', 'Aron', 'ココドラ', 3, 'Commun', 'Steel', 'Rock', 'sons/pokemon/304.ogg'),
    ('Galegon.png', 'Galegon', 'Lairon', 'コドラ', 3, 'Commun', 'Steel', 'Rock', 'sons/pokemon/305.ogg'),
    ('Galeking.png', 'Galeking', 'Aggron', 'ボスゴドラ', 3, 'Commun', 'Steel', 'Rock', 'sons/pokemon/306.ogg'),
    ('Méditikka.png', 'Méditikka', 'Meditite', 'アサナン', 3, 'Commun', 'Fighting', 'Psychic', 'sons/pokemon/307.ogg'),
    ('Charmina.png', 'Charmina', 'Medicham', 'チャーレム', 3, 'Commun', 'Fighting', 'Psychic', 'sons/pokemon/308.ogg'),
    ('Dynavolt.png', 'Dynavolt', 'Electrike', 'ラクライ', 3, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/309.ogg'),
    ('Élecsprint.png', 'Élecsprint', 'Manectric', 'ライボルト', 3, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/310.ogg'),
    ('Posipi.png', 'Posipi', 'Plusle', 'プラスル', 3, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/311.ogg'),
    ('Négapi.png', 'Négapi', 'Minun', 'マイナン', 3, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/312.ogg'),
    ('Muciole.png', 'Muciole', 'Volbeat', 'バルビート', 3, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/313.ogg'),
    ('Lumivole.png', 'Lumivole', 'Illumise', 'イルミーゼ', 3, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/314.ogg'),
    ('Rosélia.png', 'Rosélia', 'Roselia', 'ロゼリア', 3, 'Commun', 'Grass', 'Poison', 'sons/pokemon/315.ogg'),
    ('Gloupti.png', 'Gloupti', 'Gulpin', 'ゴクリン', 3, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/316.ogg'),
    ('Avaltout.png', 'Avaltout', 'Swalot', 'マルノーム', 3, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/317.ogg'),
    ('Carvanha.png', 'Carvanha', 'Carvanha', 'キバニア', 3, 'Commun', 'Water', 'Dark', 'sons/pokemon/318.ogg'),
    ('Sharpedo.png', 'Sharpedo', 'Sharpedo', 'サメハダー', 3, 'Commun', 'Water', 'Dark', 'sons/pokemon/319.ogg'),
    ('Wailmer.png', 'Wailmer', 'Wailmer', 'ホエルコ', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/320.ogg'),
    ('Wailord.png', 'Wailord', 'Wailord', 'ホエルオー', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/321.ogg'),
    ('Chamallot.png', 'Chamallot', 'Numel', 'ドンメル', 3, 'Commun', 'Fire', 'Ground', 'sons/pokemon/322.ogg'),
    ('Camérupt.png', 'Camérupt', 'Camerupt', 'バクーダ', 3, 'Commun', 'Fire', 'Ground', 'sons/pokemon/323.ogg'),
    ('Chartor.png', 'Chartor', 'Torkoal', 'コータス', 3, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/324.ogg'),
    ('Spoink.png', 'Spoink', 'Spoink', 'バネブー', 3, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/325.ogg'),
    ('Groret.png', 'Groret', 'Grumpig', 'ブーピッグ', 3, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/326.ogg'),
    ('Spinda.png', 'Spinda', 'Spinda', 'パッチール', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/327.ogg'),
    ('Kraknoix.png', 'Kraknoix', 'Trapinch', 'ナックラー', 3, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/328.ogg'),
    ('Vibraninf.png', 'Vibraninf', 'Vibrava', 'ビブラーバ', 3, 'Commun', 'Ground', 'Dragon', 'sons/pokemon/329.ogg'),
    ('Libégon.png', 'Libégon', 'Flygon', 'フライゴン', 3, 'Commun', 'Ground', 'Dragon', 'sons/pokemon/330.ogg'),
    ('Cacnea.png', 'Cacnea', 'Cacnea', 'サボネア', 3, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/331.ogg'),
    ('Cacturne.png', 'Cacturne', 'Cacturne', 'ノクタス', 3, 'Commun', 'Grass', 'Dark', 'sons/pokemon/332.ogg'),
    ('Tylton.png', 'Tylton', 'Swablu', 'チルット', 3, 'Commun', 'Normal', 'Flying', 'sons/pokemon/333.ogg'),
    ('Altaria.png', 'Altaria', 'Altaria', 'チルタリス', 3, 'Commun', 'Dragon', 'Flying', 'sons/pokemon/334.ogg'),
    ('Mangriff.png', 'Mangriff', 'Zangoose', 'ザングース', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/335.ogg'),
    ('Séviper.png', 'Séviper', 'Seviper', 'ハブネーク', 3, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/336.ogg'),
    ('Séléroc.png', 'Séléroc', 'Lunatone', 'ルナトーン', 3, 'Commun', 'Rock', 'Psychic', 'sons/pokemon/337.ogg'),
    ('Solaroc.png', 'Solaroc', 'Solrock', 'ソルロック', 3, 'Commun', 'Rock', 'Psychic', 'sons/pokemon/338.ogg'),
    ('Barloche.png', 'Barloche', 'Barboach', 'ドジョッチ', 3, 'Commun', 'Water', 'Ground', 'sons/pokemon/339.ogg'),
    ('Barbicha.png', 'Barbicha', 'Whiscash', 'ナマズン', 3, 'Commun', 'Water', 'Ground', 'sons/pokemon/340.ogg'),
    ('Écrapince.png', 'Écrapince', 'Corphish', 'ヘイガニ', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/341.ogg'),
    ('Colhomard.png', 'Colhomard', 'Crawdaunt', 'シザリガー', 3, 'Commun', 'Water', 'Dark', 'sons/pokemon/342.ogg'),
    ('Balbuto.png', 'Balbuto', 'Baltoy', 'ヤジロン', 3, 'Commun', 'Ground', 'Psychic', 'sons/pokemon/343.ogg'),
    ('Kaorine.png', 'Kaorine', 'Claydol', 'ネンドール', 3, 'Commun', 'Ground', 'Psychic', 'sons/pokemon/344.ogg'),
    ('Lilia.png', 'Lilia', 'Lileep', 'リリーラ', 3, 'Commun', 'Rock', 'Grass', 'sons/pokemon/345.ogg'),
    ('Vacilys.png', 'Vacilys', 'Cradily', 'ユレイドル', 3, 'Commun', 'Rock', 'Grass', 'sons/pokemon/346.ogg'),
    ('Anorith.png', 'Anorith', 'Anorith', 'アノプス', 3, 'Commun', 'Rock', 'Bug', 'sons/pokemon/347.ogg'),
    ('Armaldo.png', 'Armaldo', 'Armaldo', 'アーマルド', 3, 'Commun', 'Rock', 'Bug', 'sons/pokemon/348.ogg'),
    ('Barpau.png', 'Barpau', 'Feebas', 'ヒンバス', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/349.ogg'),
    ('Milobellus.png', 'Milobellus', 'Milotic', 'ミロカロス', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/350.ogg'),
    ('Morphéo.png', 'Morphéo', 'Castform', 'ポワルン', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/351.ogg'),
    ('Kecleon.png', 'Kecleon', 'Kecleon', 'カクレオン', 3, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/352.ogg'),
    ('Polichombr.png', 'Polichombr', 'Shuppet', 'カゲボウズ', 3, 'Commun', 'Ghost', 'Aucun', 'sons/pokemon/353.ogg'),
    ('Branette.png', 'Branette', 'Banette', 'ジュペッタ', 3, 'Commun', 'Ghost', 'Aucun', 'sons/pokemon/354.ogg'),
    ('Skelénox.png', 'Skelénox', 'Duskull', 'ヨマワル', 3, 'Commun', 'Ghost', 'Aucun', 'sons/pokemon/355.ogg'),
    ('Téraclope.png', 'Téraclope', 'Dusclops', 'サマヨール', 3, 'Commun', 'Ghost', 'Aucun', 'sons/pokemon/356.ogg'),
    ('Tropius.png', 'Tropius', 'Tropius', 'トロピウス', 3, 'Commun', 'Grass', 'Flying', 'sons/pokemon/357.ogg'),
    ('Éoko.png', 'Éoko', 'Chimecho', 'チリーン', 3, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/358.ogg'),
    ('Absol.png', 'Absol', 'Absol', 'アブソル', 3, 'Commun', 'Dark', 'Aucun', 'sons/pokemon/359.ogg'),
    ('Okéoké.png', 'Okéoké', 'Wynaut', 'ソーナノ', 3, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/360.ogg'),
    ('Stalgamin.png', 'Stalgamin', 'Snorunt', 'ユキワラシ', 3, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/361.ogg'),
    ('Oniglali.png', 'Oniglali', 'Glalie', 'オニゴーリ', 3, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/362.ogg'),
    ('Obalie.png', 'Obalie', 'Spheal', 'タマザラシ', 3, 'Commun', 'Ice', 'Water', 'sons/pokemon/363.ogg'),
    ('Phogleur.png', 'Phogleur', 'Sealeo', 'トドグラー', 3, 'Commun', 'Ice', 'Water', 'sons/pokemon/364.ogg'),
    ('Kaimorse.png', 'Kaimorse', 'Walrein', 'トドゼルガ', 3, 'Commun', 'Ice', 'Water', 'sons/pokemon/365.ogg'),
    ('Coquiperl.png', 'Coquiperl', 'Clamperl', 'パールル', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/366.ogg'),
    ('Serpang.png', 'Serpang', 'Huntail', 'ハンテール', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/367.ogg'),
    ('Rosabyss.png', 'Rosabyss', 'Gorebyss', 'サクラビス', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/368.ogg'),
    ('Relicanth.png', 'Relicanth', 'Relicanth', 'ジーランス', 3, 'Commun', 'Water', 'Rock', 'sons/pokemon/369.ogg'),
    ('Lovdisc.png', 'Lovdisc', 'Luvdisc', 'ラブカス', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/370.ogg'),
    ('Draby.png', 'Draby', 'Bagon', 'タツベイ', 3, 'Commun', 'Dragon', 'Aucun', 'sons/pokemon/371.ogg'),
    ('Drackhaus.png', 'Drackhaus', 'Shelgon', 'コモルー', 3, 'Commun', 'Dragon', 'Aucun', 'sons/pokemon/372.ogg'),
    ('Drattak.png', 'Drattak', 'Salamence', 'ボーマンダ', 3, 'Commun', 'Dragon', 'Flying', 'sons/pokemon/373.ogg'),
    ('Terhal.png', 'Terhal', 'Beldum', 'ダンバル', 3, 'Commun', 'Steel', 'Psychic', 'sons/pokemon/374.ogg'),
    ('Métang.png', 'Métang', 'Metang', 'メタング', 3, 'Commun', 'Steel', 'Psychic', 'sons/pokemon/375.ogg'),
    ('Métalosse.png', 'Métalosse', 'Metagross', 'メタグロス', 3, 'Commun', 'Steel', 'Psychic', 'sons/pokemon/376.ogg'),
    ('Regirock.png', 'Regirock', 'Regirock', 'レジロック', 3, 'Commun', 'Rock', 'Aucun', 'sons/pokemon/377.ogg'),
    ('Regice.png', 'Regice', 'Regice', 'レジアイス', 3, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/378.ogg'),
    ('Registeel.png', 'Registeel', 'Registeel', 'レジスチル', 3, 'Commun', 'Steel', 'Aucun', 'sons/pokemon/379.ogg'),
    ('Latias.png', 'Latias', 'Latias', 'ラティアス', 3, 'Commun', 'Dragon', 'Psychic', 'sons/pokemon/380.ogg'),
    ('Latios.png', 'Latios', 'Latios', 'ラティオス', 3, 'Commun', 'Dragon', 'Psychic', 'sons/pokemon/381.ogg'),
    ('Kyogre.png', 'Kyogre', 'Kyogre', 'カイオーガ', 3, 'Commun', 'Water', 'Aucun', 'sons/pokemon/382.ogg'),
    ('Groudon.png', 'Groudon', 'Groudon', 'グラードン', 3, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/383.ogg'),
    ('Rayquaza.png', 'Rayquaza', 'Rayquaza', 'レックウザ', 3, 'Commun', 'Dragon', 'Flying', 'sons/pokemon/384.ogg'),
    ('Jirachi.png', 'Jirachi', 'Jirachi', 'ジラーチ', 3, 'Commun', 'Steel', 'Psychic', 'sons/pokemon/385.ogg'),
    ('Deoxys.png', 'Deoxys', 'Deoxys', 'デオキシス', 3, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/386.ogg'),
    ('Tortipouss.png', 'Tortipouss', 'Turtwig', 'ナエトル', 4, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/387.ogg'),
    ('Boskara.png', 'Boskara', 'Grotle', 'ハヤシガメ', 4, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/388.ogg'),
    ('Torterra.png', 'Torterra', 'Torterra', 'ドダイトス', 4, 'Commun', 'Grass', 'Ground', 'sons/pokemon/389.ogg'),
    ('Ouisticram.png', 'Ouisticram', 'Chimchar', 'ヒコザル', 4, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/390.ogg'),
    ('Chimpenfeu.png', 'Chimpenfeu', 'Monferno', 'モウカザル', 4, 'Commun', 'Fire', 'Fighting', 'sons/pokemon/391.ogg'),
    ('Simiabraz.png', 'Simiabraz', 'Infernape', 'ゴウカザル', 4, 'Commun', 'Fire', 'Fighting', 'sons/pokemon/392.ogg'),
    ('Tiplouf.png', 'Tiplouf', 'Piplup', 'ポッチャマ', 4, 'Commun', 'Water', 'Aucun', 'sons/pokemon/393.ogg'),
    ('Prinplouf.png', 'Prinplouf', 'Prinplup', 'ポッタイシ', 4, 'Commun', 'Water', 'Aucun', 'sons/pokemon/394.ogg'),
    ('Pingoléon.png', 'Pingoléon', 'Empoleon', 'エンペルト', 4, 'Commun', 'Water', 'Steel', 'sons/pokemon/395.ogg'),
    ('Étourmi.png', 'Étourmi', 'Starly', 'ムックル', 4, 'Commun', 'Normal', 'Flying', 'sons/pokemon/396.ogg'),
    ('Étourvol.png', 'Étourvol', 'Staravia', 'ムクバード', 4, 'Commun', 'Normal', 'Flying', 'sons/pokemon/397.ogg'),
    ('Étouraptor.png', 'Étouraptor', 'Staraptor', 'ムクホーク', 4, 'Commun', 'Normal', 'Flying', 'sons/pokemon/398.ogg'),
    ('Keunotor.png', 'Keunotor', 'Bidoof', 'ビッパ', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/399.ogg'),
    ('Castorno.png', 'Castorno', 'Bibarel', 'ビーダル', 4, 'Commun', 'Normal', 'Water', 'sons/pokemon/400.ogg'),
    ('Crikzik.png', 'Crikzik', 'Kricketot', 'コロボーシ', 4, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/401.ogg'),
    ('Mélokrik.png', 'Mélokrik', 'Kricketune', 'コロトック', 4, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/402.ogg'),
    ('Lixy.png', 'Lixy', 'Shinx', 'コリンク', 4, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/403.ogg'),
    ('Luxio.png', 'Luxio', 'Luxio', 'ルクシオ', 4, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/404.ogg'),
    ('Luxray.png', 'Luxray', 'Luxray', 'レントラー', 4, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/405.ogg'),
    ('Rozbouton.png', 'Rozbouton', 'Budew', 'スボミー', 4, 'Commun', 'Grass', 'Poison', 'sons/pokemon/406.ogg'),
    ('Roserade.png', 'Roserade', 'Roserade', 'ロズレイド', 4, 'Commun', 'Grass', 'Poison', 'sons/pokemon/407.ogg'),
    ('Kranidos.png', 'Kranidos', 'Cranidos', 'ズガイドス', 4, 'Commun', 'Rock', 'Aucun', 'sons/pokemon/408.ogg'),
    ('Charkos.png', 'Charkos', 'Rampardos', 'ラムパルド', 4, 'Commun', 'Rock', 'Aucun', 'sons/pokemon/409.ogg'),
    ('Dinoclier.png', 'Dinoclier', 'Shieldon', 'タテトプス', 4, 'Commun', 'Rock', 'Steel', 'sons/pokemon/410.ogg'),
    ('Bastiodon.png', 'Bastiodon', 'Bastiodon', 'トリデプス', 4, 'Commun', 'Rock', 'Steel', 'sons/pokemon/411.ogg'),
    ('Cheniti.png', 'Cheniti', 'Burmy', 'ミノムッチ', 4, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/412.ogg'),
    ('Cheniselle.png', 'Cheniselle', 'Wormadam', 'ミノマダム', 4, 'Commun', 'Bug', 'Grass', 'sons/pokemon/413.ogg'),
    ('Papilord.png', 'Papilord', 'Mothim', 'ガーメイル', 4, 'Commun', 'Bug', 'Flying', 'sons/pokemon/414.ogg'),
    ('Apitrini.png', 'Apitrini', 'Combee', 'ミツハニー', 4, 'Commun', 'Bug', 'Flying', 'sons/pokemon/415.ogg'),
    ('Apireine.png', 'Apireine', 'Vespiquen', 'ビークイン', 4, 'Commun', 'Bug', 'Flying', 'sons/pokemon/416.ogg'),
    ('Pachirisu.png', 'Pachirisu', 'Pachirisu', 'パチリス', 4, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/417.ogg'),
    ('Mustébouée.png', 'Mustébouée', 'Buizel', 'ブイゼル', 4, 'Commun', 'Water', 'Aucun', 'sons/pokemon/418.ogg'),
    ('Mustéflott.png', 'Mustéflott', 'Floatzel', 'フローゼル', 4, 'Commun', 'Water', 'Aucun', 'sons/pokemon/419.ogg'),
    ('Ceribou.png', 'Ceribou', 'Cherubi', 'チェリンボ', 4, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/420.ogg'),
    ('Ceriflor.png', 'Ceriflor', 'Cherrim', 'チェリム', 4, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/421.ogg'),
    ('Sancoki.png', 'Sancoki', 'Shellos', 'カラナクシ', 4, 'Commun', 'Water', 'Aucun', 'sons/pokemon/422.ogg'),
    ('Tritosor.png', 'Tritosor', 'Gastrodon', 'トリトドン', 4, 'Commun', 'Water', 'Ground', 'sons/pokemon/423.ogg'),
    ('Capidextre.png', 'Capidextre', 'Ambipom', 'エテボース', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/424.ogg'),
    ('Baudrive.png', 'Baudrive', 'Drifloon', 'フワンテ', 4, 'Commun', 'Ghost', 'Flying', 'sons/pokemon/425.ogg'),
    ('Grodrive.png', 'Grodrive', 'Drifblim', 'フワライド', 4, 'Commun', 'Ghost', 'Flying', 'sons/pokemon/426.ogg'),
    ('Laporeille.png', 'Laporeille', 'Buneary', 'ミミロル', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/427.ogg'),
    ('Lockpin.png', 'Lockpin', 'Lopunny', 'ミミロップ', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/428.ogg'),
    ('Magirêve.png', 'Magirêve', 'Mismagius', 'ムウマージ', 4, 'Commun', 'Ghost', 'Aucun', 'sons/pokemon/429.ogg'),
    ('Corboss.png', 'Corboss', 'Honchkrow', 'ドンカラス', 4, 'Commun', 'Dark', 'Flying', 'sons/pokemon/430.ogg'),
    ('Chaglam.png', 'Chaglam', 'Glameow', 'ニャルマー', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/431.ogg'),
    ('Chaffreux.png', 'Chaffreux', 'Purugly', 'ブニャット', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/432.ogg'),
    ('Korillon.png', 'Korillon', 'Chingling', 'リーシャン', 4, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/433.ogg'),
    ('Moufouette.png', 'Moufouette', 'Stunky', 'スカンプー', 4, 'Commun', 'Poison', 'Dark', 'sons/pokemon/434.ogg'),
    ('Moufflair.png', 'Moufflair', 'Skuntank', 'スカタンク', 4, 'Commun', 'Poison', 'Dark', 'sons/pokemon/435.ogg'),
    ('Archéomire.png', 'Archéomire', 'Bronzor', 'ドーミラー', 4, 'Commun', 'Steel', 'Psychic', 'sons/pokemon/436.ogg'),
    ('Archéodong.png', 'Archéodong', 'Bronzong', 'ドータクン', 4, 'Commun', 'Steel', 'Psychic', 'sons/pokemon/437.ogg'),
    ('Manzaï.png', 'Manzaï', 'Bonsly', 'ウソハチ', 4, 'Commun', 'Rock', 'Aucun', 'sons/pokemon/438.ogg'),
    ('Mime Jr.png', 'Mime Jr', 'Mime Jr.', 'マネネ', 4, 'Commun', 'Psychic', 'Fairy', 'sons/pokemon/439.ogg'),
    ('Ptiravi.png', 'Ptiravi', 'Happiny', 'ピンプク', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/440.ogg'),
    ('Pijako.png', 'Pijako', 'Chatot', 'ペラップ', 4, 'Commun', 'Normal', 'Flying', 'sons/pokemon/441.ogg'),
    ('Spiritomb.png', 'Spiritomb', 'Spiritomb', 'ミカルゲ', 4, 'Commun', 'Ghost', 'Dark', 'sons/pokemon/442.ogg'),
    ('Griknot.png', 'Griknot', 'Gible', 'フカマル', 4, 'Commun', 'Dragon', 'Ground', 'sons/pokemon/443.ogg'),
    ('Carmache.png', 'Carmache', 'Gabite', 'ガバイト', 4, 'Commun', 'Dragon', 'Ground', 'sons/pokemon/444.ogg'),
    ('Carchacrok.png', 'Carchacrok', 'Garchomp', 'ガブリアス', 4, 'Commun', 'Dragon', 'Ground', 'sons/pokemon/445.ogg'),
    ('Goinfrex.png', 'Goinfrex', 'Munchlax', 'ゴンベ', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/446.ogg'),
    ('Riolu.png', 'Riolu', 'Riolu', 'リオル', 4, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/447.ogg'),
    ('Lucario.png', 'Lucario', 'Lucario', 'ルカリオ', 4, 'Commun', 'Fighting', 'Steel', 'sons/pokemon/448.ogg'),
    ('Hippopotas.png', 'Hippopotas', 'Hippopotas', 'ヒポポタス', 4, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/449.ogg'),
    ('Hippodocus.png', 'Hippodocus', 'Hippowdon', 'カバルドン', 4, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/450.ogg'),
    ('Rapion.png', 'Rapion', 'Skorupi', 'スコルピ', 4, 'Commun', 'Poison', 'Bug', 'sons/pokemon/451.ogg'),
    ('Drascore.png', 'Drascore', 'Drapion', 'ドラピオン', 4, 'Commun', 'Poison', 'Dark', 'sons/pokemon/452.ogg'),
    ('Cradopaud.png', 'Cradopaud', 'Croagunk', 'グレッグル', 4, 'Commun', 'Poison', 'Fighting', 'sons/pokemon/453.ogg'),
    ('Coatox.png', 'Coatox', 'Toxicroak', 'ドクロッグ', 4, 'Commun', 'Poison', 'Fighting', 'sons/pokemon/454.ogg'),
    ('Vortente.png', 'Vortente', 'Carnivine', 'マスキッパ', 4, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/455.ogg'),
    ('Écayon.png', 'Écayon', 'Finneon', 'ケイコウオ', 4, 'Commun', 'Water', 'Aucun', 'sons/pokemon/456.ogg'),
    ('Luminéon.png', 'Luminéon', 'Lumineon', 'ネオラント', 4, 'Commun', 'Water', 'Aucun', 'sons/pokemon/457.ogg'),
    ('Babimanta.png', 'Babimanta', 'Mantyke', 'タマンタ', 4, 'Commun', 'Water', 'Flying', 'sons/pokemon/458.ogg'),
    ('Blizzi.png', 'Blizzi', 'Snover', 'ユキカブリ', 4, 'Commun', 'Grass', 'Ice', 'sons/pokemon/459.ogg'),
    ('Blizzaroi.png', 'Blizzaroi', 'Abomasnow', 'ユキノオー', 4, 'Commun', 'Grass', 'Ice', 'sons/pokemon/460.ogg'),
    ('Dimoret.png', 'Dimoret', 'Weavile', 'マニューラ', 4, 'Commun', 'Dark', 'Ice', 'sons/pokemon/461.ogg'),
    ('Magnézone.png', 'Magnézone', 'Magnezone', 'ジバコイル', 4, 'Commun', 'Electric', 'Steel', 'sons/pokemon/462.ogg'),
    ('Coudlangue.png', 'Coudlangue', 'Lickilicky', 'ベロベルト', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/463.ogg'),
    ('Rhinastoc.png', 'Rhinastoc', 'Rhyperior', 'ドサイドン', 4, 'Commun', 'Ground', 'Rock', 'sons/pokemon/464.ogg'),
    ('Bouldeneu.png', 'Bouldeneu', 'Tangrowth', 'モジャンボ', 4, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/465.ogg'),
    ('Élekable.png', 'Élekable', 'Electivire', 'エレキブル', 4, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/466.ogg'),
    ('Maganon.png', 'Maganon', 'Magmortar', 'ブーバーン', 4, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/467.ogg'),
    ('Togekiss.png', 'Togekiss', 'Togekiss', 'トゲキッス', 4, 'Commun', 'Fairy', 'Flying', 'sons/pokemon/468.ogg'),
    ('Yanmega.png', 'Yanmega', 'Yanmega', 'メガヤンマ', 4, 'Commun', 'Bug', 'Flying', 'sons/pokemon/469.ogg'),
    ('Phyllali.png', 'Phyllali', 'Leafeon', 'リーフィア', 4, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/470.ogg'),
    ('Givrali.png', 'Givrali', 'Glaceon', 'グレイシア', 4, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/471.ogg'),
    ('Scorvol.png', 'Scorvol', 'Gliscor', 'グライオン', 4, 'Commun', 'Ground', 'Flying', 'sons/pokemon/472.ogg'),
    ('Mammochon.png', 'Mammochon', 'Mamoswine', 'マンムー', 4, 'Commun', 'Ice', 'Ground', 'sons/pokemon/473.ogg'),
    ('Porygon-Z.png', 'Porygon-Z', 'Porygon-Z', 'ポリゴンＺ', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/474.ogg'),
    ('Gallame.png', 'Gallame', 'Gallade', 'エルレイド', 4, 'Commun', 'Psychic', 'Fighting', 'sons/pokemon/475.ogg'),
    ('Tarinorme.png', 'Tarinorme', 'Probopass', 'ダイノーズ', 4, 'Commun', 'Rock', 'Steel', 'sons/pokemon/476.ogg'),
    ('Noctunoir.png', 'Noctunoir', 'Dusknoir', 'ヨノワール', 4, 'Commun', 'Ghost', 'Aucun', 'sons/pokemon/477.ogg'),
    ('Momartik.png', 'Momartik', 'Froslass', 'ユキメノコ', 4, 'Commun', 'Ice', 'Ghost', 'sons/pokemon/478.ogg'),
    ('Motisma.png', 'Motisma', 'Rotom', 'ロトム', 4, 'Commun', 'Electric', 'Ghost', 'sons/pokemon/479.ogg'),
    ('Créhelf.png', 'Créhelf', 'Uxie', 'ユクシー', 4, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/480.ogg'),
    ('Créfollet.png', 'Créfollet', 'Mesprit', 'エムリット', 4, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/481.ogg'),
    ('Créfadet.png', 'Créfadet', 'Azelf', 'アグノム', 4, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/482.ogg'),
    ('Dialga.png', 'Dialga', 'Dialga', 'ディアルガ', 4, 'Commun', 'Steel', 'Dragon', 'sons/pokemon/483.ogg'),
    ('Palkia.png', 'Palkia', 'Palkia', 'パルキア', 4, 'Commun', 'Water', 'Dragon', 'sons/pokemon/484.ogg'),
    ('Heatran.png', 'Heatran', 'Heatran', 'ヒードラン', 4, 'Commun', 'Fire', 'Steel', 'sons/pokemon/485.ogg'),
    ('Regigigas.png', 'Regigigas', 'Regigigas', 'レジギガス', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/486.ogg'),
    ('Giratina.png', 'Giratina', 'Giratina', 'ギラティナ', 4, 'Commun', 'Ghost', 'Dragon', 'sons/pokemon/487.ogg'),
    ('Cresselia.png', 'Cresselia', 'Cresselia', 'クレセリア', 4, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/488.ogg'),
    ('Phione.png', 'Phione', 'Phione', 'フィオネ', 4, 'Commun', 'Water', 'Aucun', 'sons/pokemon/489.ogg'),
    ('Manaphy.png', 'Manaphy', 'Manaphy', 'マナフィ', 4, 'Commun', 'Water', 'Aucun', 'sons/pokemon/490.ogg'),
    ('Darkrai.png', 'Darkrai', 'Darkrai', 'ダークライ', 4, 'Commun', 'Dark', 'Aucun', 'sons/pokemon/491.ogg'),
    ('Shaymin.png', 'Shaymin', 'Shaymin', 'シェイミ', 4, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/492.ogg'),
    ('Arceus.png', 'Arceus', 'Arceus', 'アルセウス', 4, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/493.ogg'),
    ('Victini.png', 'Victini', 'Victini', 'ビクティニ', 5, 'Commun', 'Psychic', 'Fire', 'sons/pokemon/494.ogg'),
    ('Vipélierre.png', 'Vipélierre', 'Snivy', 'ツタージャ', 5, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/495.ogg'),
    ('Lianaja.png', 'Lianaja', 'Servine', 'ジャノビー', 5, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/496.ogg'),
    ('Majaspic.png', 'Majaspic', 'Serperior', 'ジャローダ', 5, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/497.ogg'),
    ('Gruikui.png', 'Gruikui', 'Tepig', 'ポカブ', 5, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/498.ogg'),
    ('Grotichon.png', 'Grotichon', 'Pignite', 'チャオブー', 5, 'Commun', 'Fire', 'Fighting', 'sons/pokemon/499.ogg'),
    ('Roitiflam.png', 'Roitiflam', 'Emboar', 'エンブオー', 5, 'Commun', 'Fire', 'Fighting', 'sons/pokemon/500.ogg'),
    ('Moustillon.png', 'Moustillon', 'Oshawott', 'ミジュマル', 5, 'Commun', 'Water', 'Aucun', 'sons/pokemon/501.ogg'),
    ('Mateloutre.png', 'Mateloutre', 'Dewott', 'フタチマル', 5, 'Commun', 'Water', 'Aucun', 'sons/pokemon/502.ogg'),
    ('Clamiral.png', 'Clamiral', 'Samurott', 'ダイケンキ', 5, 'Commun', 'Water', 'Aucun', 'sons/pokemon/503.ogg'),
    ('Ratentif.png', 'Ratentif', 'Patrat', 'ミネズミ', 5, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/504.ogg'),
    ('Miradar.png', 'Miradar', 'Watchog', 'ミルホッグ', 5, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/505.ogg'),
    ('Ponchiot.png', 'Ponchiot', 'Lillipup', 'ヨーテリー', 5, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/506.ogg'),
    ('Ponchien.png', 'Ponchien', 'Herdier', 'ハーデリア', 5, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/507.ogg'),
    ('Mastouffe.png', 'Mastouffe', 'Stoutland', 'ムーランド', 5, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/508.ogg'),
    ('Chacripan.png', 'Chacripan', 'Purrloin', 'チョロネコ', 5, 'Commun', 'Dark', 'Aucun', 'sons/pokemon/509.ogg'),
    ('Léopardus.png', 'Léopardus', 'Liepard', 'レパルダス', 5, 'Commun', 'Dark', 'Aucun', 'sons/pokemon/510.ogg'),
    ('Feuillajou.png', 'Feuillajou', 'Pansage', 'ヤナップ', 5, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/511.ogg'),
    ('Feuiloutan.png', 'Feuiloutan', 'Simisage', 'ヤナッキー', 5, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/512.ogg'),
    ('Flamajou.png', 'Flamajou', 'Pansear', 'バオップ', 5, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/513.ogg'),
    ('Flamoutan.png', 'Flamoutan', 'Simisear', 'バオッキー', 5, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/514.ogg'),
    ('Flotajou.png', 'Flotajou', 'Panpour', 'ヒヤップ', 5, 'Commun', 'Water', 'Aucun', 'sons/pokemon/515.ogg'),
    ('Flotoutan.png', 'Flotoutan', 'Simipour', 'ヒヤッキー', 5, 'Commun', 'Water', 'Aucun', 'sons/pokemon/516.ogg'),
    ('Munna.png', 'Munna', 'Munna', 'ムンナ', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/517.ogg'),
    ('Mushana.png', 'Mushana', 'Musharna', 'ムシャーナ', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/518.ogg'),
    ('Poichigeon.png', 'Poichigeon', 'Pidove', 'マメパト', 5, 'Commun', 'Normal', 'Flying', 'sons/pokemon/519.ogg'),
    ('Colombeau.png', 'Colombeau', 'Tranquill', 'ハトーボー', 5, 'Commun', 'Normal', 'Flying', 'sons/pokemon/520.ogg'),
    ('Déflaisan.png', 'Déflaisan', 'Unfezant', 'ケンホロウ', 5, 'Commun', 'Normal', 'Flying', 'sons/pokemon/521.ogg'),
    ('Zébibron.png', 'Zébibron', 'Blitzle', 'シママ', 5, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/522.ogg'),
    ('Zéblitz.png', 'Zéblitz', 'Zebstrika', 'ゼブライカ', 5, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/523.ogg'),
    ('Nodulithe.png', 'Nodulithe', 'Roggenrola', 'ダンゴロ', 5, 'Commun', 'Rock', 'Aucun', 'sons/pokemon/524.ogg'),
    ('Géolithe.png', 'Géolithe', 'Boldore', 'ガントル', 5, 'Commun', 'Rock', 'Aucun', 'sons/pokemon/525.ogg'),
    ('Gigalithe.png', 'Gigalithe', 'Gigalith', 'ギガイアス', 5, 'Commun', 'Rock', 'Aucun', 'sons/pokemon/526.ogg'),
    ('Chovsourir.png', 'Chovsourir', 'Woobat', 'コロモリ', 5, 'Commun', 'Psychic', 'Flying', 'sons/pokemon/527.ogg'),
    ('Rhinolove.png', 'Rhinolove', 'Swoobat', 'ココロモリ', 5, 'Commun', 'Psychic', 'Flying', 'sons/pokemon/528.ogg'),
    ('Rototaupe.png', 'Rototaupe', 'Drilbur', 'モグリュー', 5, 'Commun', 'Ground', 'Aucun', 'sons/pokemon/529.ogg'),
    ('Minotaupe.png', 'Minotaupe', 'Excadrill', 'ドリュウズ', 5, 'Commun', 'Ground', 'Steel', 'sons/pokemon/530.ogg'),
    ('Nanméouïe.png', 'Nanméouïe', 'Audino', 'タブンネ', 5, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/531.ogg'),
    ('Charpenti.png', 'Charpenti', 'Timburr', 'ドッコラー', 5, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/532.ogg'),
    ('Ouvrifier.png', 'Ouvrifier', 'Gurdurr', 'ドテッコツ', 5, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/533.ogg'),
    ('Bétochef.png', 'Bétochef', 'Conkeldurr', 'ローブシン', 5, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/534.ogg'),
    ('Tritonde.png', 'Tritonde', 'Tympole', 'オタマロ', 5, 'Commun', 'Water', 'Aucun', 'sons/pokemon/535.ogg'),
    ('Batracné.png', 'Batracné', 'Palpitoad', 'ガマガル', 5, 'Commun', 'Water', 'Ground', 'sons/pokemon/536.ogg'),
    ('Crapustule.png', 'Crapustule', 'Seismitoad', 'ガマゲロゲ', 5, 'Commun', 'Water', 'Ground', 'sons/pokemon/537.ogg'),
    ('Judokrak.png', 'Judokrak', 'Throh', 'ナゲキ', 5, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/538.ogg'),
    ('Karaclée.png', 'Karaclée', 'Sawk', 'ダゲキ', 5, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/539.ogg'),
    ('Larveyette.png', 'Larveyette', 'Sewaddle', 'クルミル', 5, 'Commun', 'Bug', 'Grass', 'sons/pokemon/540.ogg'),
    ('Couverdure.png', 'Couverdure', 'Swadloon', 'クルマユ', 5, 'Commun', 'Bug', 'Grass', 'sons/pokemon/541.ogg'),
    ('Manternel.png', 'Manternel', 'Leavanny', 'ハハコモリ', 5, 'Commun', 'Bug', 'Grass', 'sons/pokemon/542.ogg'),
    ('Venipatte.png', 'Venipatte', 'Venipede', 'フシデ', 5, 'Commun', 'Bug', 'Poison', 'sons/pokemon/543.ogg'),
    ('Scobolide.png', 'Scobolide', 'Whirlipede', 'ホイーガ', 5, 'Commun', 'Bug', 'Poison', 'sons/pokemon/544.ogg'),
    ('Brutapode.png', 'Brutapode', 'Scolipede', 'ペンドラー', 5, 'Commun', 'Bug', 'Poison', 'sons/pokemon/545.ogg'),
    ('Doudouvet.png', 'Doudouvet', 'Cottonee', 'モンメン', 5, 'Commun', 'Grass', 'Fairy', 'sons/pokemon/546.ogg'),
    ('Farfaduvet.png', 'Farfaduvet', 'Whimsicott', 'エルフーン', 5, 'Commun', 'Grass', 'Fairy', 'sons/pokemon/547.ogg'),
    ('Chlorobule.png', 'Chlorobule', 'Petilil', 'チュリネ', 5, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/548.ogg'),
    ('Fragilady.png', 'Fragilady', 'Lilligant', 'ドレディア', 5, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/549.ogg'),
    ('Bargantua.png', 'Bargantua', 'Basculin', 'バスラオ', 5, 'Commun', 'Water', 'Aucun', 'sons/pokemon/550.ogg'),
    ('Mascaïman.png', 'Mascaïman', 'Sandile', 'メグロコ', 5, 'Commun', 'Ground', 'Dark', 'sons/pokemon/551.ogg'),
    ('Escroco.png', 'Escroco', 'Krokorok', 'ワルビル', 5, 'Commun', 'Ground', 'Dark', 'sons/pokemon/552.ogg'),
    ('Crocorible.png', 'Crocorible', 'Krookodile', 'ワルビアル', 5, 'Commun', 'Ground', 'Dark', 'sons/pokemon/553.ogg'),
    ('Darumarond.png', 'Darumarond', 'Darumaka', 'ダルマッカ', 5, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/554.ogg'),
    ('Darumacho.png', 'Darumacho', 'Darmanitan', 'ヒヒダルマ', 5, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/555.ogg'),
    ('Maracachi.png', 'Maracachi', 'Maractus', 'マラカッチ', 5, 'Commun', 'Grass', 'Aucun', 'sons/pokemon/556.ogg'),
    ('Crabicoque.png', 'Crabicoque', 'Dwebble', 'イシズマイ', 5, 'Commun', 'Bug', 'Rock', 'sons/pokemon/557.ogg'),
    ('Crabaraque.png', 'Crabaraque', 'Crustle', 'イワパレス', 5, 'Commun', 'Bug', 'Rock', 'sons/pokemon/558.ogg'),
    ('Baggiguane.png', 'Baggiguane', 'Scraggy', 'ズルッグ', 5, 'Commun', 'Dark', 'Fighting', 'sons/pokemon/559.ogg'),
    ('Baggaïd.png', 'Baggaïd', 'Scrafty', 'ズルズキン', 5, 'Commun', 'Dark', 'Fighting', 'sons/pokemon/560.ogg'),
    ('Cryptéro.png', 'Cryptéro', 'Sigilyph', 'シンボラー', 5, 'Commun', 'Psychic', 'Flying', 'sons/pokemon/561.ogg'),
    ('Tutafeh.png', 'Tutafeh', 'Yamask', 'デスマス', 5, 'Commun', 'Ghost', 'Aucun', 'sons/pokemon/562.ogg'),
    ('Tutankafer.png', 'Tutankafer', 'Cofagrigus', 'デスカーン', 5, 'Commun', 'Ghost', 'Aucun', 'sons/pokemon/563.ogg'),
    ('Carapagos.png', 'Carapagos', 'Tirtouga', 'プロトーガ', 5, 'Commun', 'Water', 'Rock', 'sons/pokemon/564.ogg'),
    ('Mégapagos.png', 'Mégapagos', 'Carracosta', 'アバゴーラ', 5, 'Commun', 'Water', 'Rock', 'sons/pokemon/565.ogg'),
    ('Arkéapti.png', 'Arkéapti', 'Archen', 'アーケン', 5, 'Commun', 'Rock', 'Flying', 'sons/pokemon/566.ogg'),
    ('Aéroptéryx.png', 'Aéroptéryx', 'Archeops', 'アーケオス', 5, 'Commun', 'Rock', 'Flying', 'sons/pokemon/567.ogg'),
    ('Miamiasme.png', 'Miamiasme', 'Trubbish', 'ヤブクロン', 5, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/568.ogg'),
    ('Miasmax.png', 'Miasmax', 'Garbodor', 'ダストダス', 5, 'Commun', 'Poison', 'Aucun', 'sons/pokemon/569.ogg'),
    ('Zorua.png', 'Zorua', 'Zorua', 'ゾロア', 5, 'Commun', 'Dark', 'Aucun', 'sons/pokemon/570.ogg'),
    ('Zoroark.png', 'Zoroark', 'Zoroark', 'ゾロアーク', 5, 'Commun', 'Dark', 'Aucun', 'sons/pokemon/571.ogg'),
    ('Chinchidou.png', 'Chinchidou', 'Minccino', 'チラーミィ', 5, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/572.ogg'),
    ('Pashmilla.png', 'Pashmilla', 'Cinccino', 'チラチーノ', 5, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/573.ogg'),
    ('Scrutella.png', 'Scrutella', 'Gothita', 'ゴチム', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/574.ogg'),
    ('Mesmérella.png', 'Mesmérella', 'Gothorita', 'ゴチミル', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/575.ogg'),
    ('Sidérella.png', 'Sidérella', 'Gothitelle', 'ゴチルゼル', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/576.ogg'),
    ('Nucléos.png', 'Nucléos', 'Solosis', 'ユニラン', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/577.ogg'),
    ('Méios.png', 'Méios', 'Duosion', 'ダブラン', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/578.ogg'),
    ('Symbios.png', 'Symbios', 'Reuniclus', 'ランクルス', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/579.ogg'),
    ('Couaneton.png', 'Couaneton', 'Ducklett', 'コアルヒー', 5, 'Commun', 'Water', 'Flying', 'sons/pokemon/580.ogg'),
    ('Lakmécygne.png', 'Lakmécygne', 'Swanna', 'スワンナ', 5, 'Commun', 'Water', 'Flying', 'sons/pokemon/581.ogg'),
    ('Sorbébé.png', 'Sorbébé', 'Vanillite', 'バニプッチ', 5, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/582.ogg'),
    ('Sorboul.png', 'Sorboul', 'Vanillish', 'バニリッチ', 5, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/583.ogg'),
    ('Sorbouboul.png', 'Sorbouboul', 'Vanilluxe', 'バイバニラ', 5, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/584.ogg'),
    ('Vivaldaim.png', 'Vivaldaim', 'Deerling', 'シキジカ', 5, 'Commun', 'Normal', 'Grass', 'sons/pokemon/585.ogg'),
    ('Haydaim.png', 'Haydaim', 'Sawsbuck', 'メブキジカ', 5, 'Commun', 'Normal', 'Grass', 'sons/pokemon/586.ogg'),
    ('Emolga.png', 'Emolga', 'Emolga', 'エモンガ', 5, 'Commun', 'Electric', 'Flying', 'sons/pokemon/587.ogg'),
    ('Carabing.png', 'Carabing', 'Karrablast', 'カブルモ', 5, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/588.ogg'),
    ('Lançargot.png', 'Lançargot', 'Escavalier', 'シュバルゴ', 5, 'Commun', 'Bug', 'Steel', 'sons/pokemon/589.ogg'),
    ('Trompignon.png', 'Trompignon', 'Foongus', 'タマゲタケ', 5, 'Commun', 'Grass', 'Poison', 'sons/pokemon/590.ogg'),
    ('Gaulet.png', 'Gaulet', 'Amoonguss', 'モロバレル', 5, 'Commun', 'Grass', 'Poison', 'sons/pokemon/591.ogg'),
    ('Viskuse.png', 'Viskuse', 'Frillish', 'プルリル', 5, 'Commun', 'Water', 'Ghost', 'sons/pokemon/592.ogg'),
    ('Moyade.png', 'Moyade', 'Jellicent', 'ブルンゲル', 5, 'Commun', 'Water', 'Ghost', 'sons/pokemon/593.ogg'),
    ('Mamanbo.png', 'Mamanbo', 'Alomomola', 'ママンボウ', 5, 'Commun', 'Water', 'Aucun', 'sons/pokemon/594.ogg'),
    ('Statitik.png', 'Statitik', 'Joltik', 'バチュル', 5, 'Commun', 'Bug', 'Electric', 'sons/pokemon/595.ogg'),
    ('Mygavolt.png', 'Mygavolt', 'Galvantula', 'デンチュラ', 5, 'Commun', 'Bug', 'Electric', 'sons/pokemon/596.ogg'),
    ('Grindur.png', 'Grindur', 'Ferroseed', 'テッシード', 5, 'Commun', 'Grass', 'Steel', 'sons/pokemon/597.ogg'),
    ('Noacier.png', 'Noacier', 'Ferrothorn', 'ナットレイ', 5, 'Commun', 'Grass', 'Steel', 'sons/pokemon/598.ogg'),
    ('Tic.png', 'Tic', 'Klink', 'ギアル', 5, 'Commun', 'Steel', 'Aucun', 'sons/pokemon/599.ogg'),
    ('Clic.png', 'Clic', 'Klang', 'ギギアル', 5, 'Commun', 'Steel', 'Aucun', 'sons/pokemon/600.ogg'),
    ('Cliticlic.png', 'Cliticlic', 'Klinklang', 'ギギギアル', 5, 'Commun', 'Steel', 'Aucun', 'sons/pokemon/601.ogg'),
    ('Anchwatt.png', 'Anchwatt', 'Tynamo', 'シビシラス', 5, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/602.ogg'),
    ('Lampéroie.png', 'Lampéroie', 'Eelektrik', 'シビビール', 5, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/603.ogg'),
    ('Ohmassacre.png', 'Ohmassacre', 'Eelektross', 'シビルドン', 5, 'Commun', 'Electric', 'Aucun', 'sons/pokemon/604.ogg'),
    ('Lewsor.png', 'Lewsor', 'Elgyem', 'リグレー', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/605.ogg'),
    ('Neitram.png', 'Neitram', 'Beheeyem', 'オーベム', 5, 'Commun', 'Psychic', 'Aucun', 'sons/pokemon/606.ogg'),
    ('Funécire.png', 'Funécire', 'Litwick', 'ヒトモシ', 5, 'Commun', 'Ghost', 'Fire', 'sons/pokemon/607.ogg'),
    ('Mélancolux.png', 'Mélancolux', 'Lampent', 'ランプラー', 5, 'Commun', 'Ghost', 'Fire', 'sons/pokemon/608.ogg'),
    ('Lugulabre.png', 'Lugulabre', 'Chandelure', 'シャンデラ', 5, 'Commun', 'Ghost', 'Fire', 'sons/pokemon/609.ogg'),
    ('Coupenotte.png', 'Coupenotte', 'Axew', 'キバゴ', 5, 'Commun', 'Dragon', 'Aucun', 'sons/pokemon/610.ogg'),
    ('Incisache.png', 'Incisache', 'Fraxure', 'オノンド', 5, 'Commun', 'Dragon', 'Aucun', 'sons/pokemon/611.ogg'),
    ('Tranchodon.png', 'Tranchodon', 'Haxorus', 'オノノクス', 5, 'Commun', 'Dragon', 'Aucun', 'sons/pokemon/612.ogg'),
    ('Polarhume.png', 'Polarhume', 'Cubchoo', 'クマシュン', 5, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/613.ogg'),
    ('Polagriffe.png', 'Polagriffe', 'Beartic', 'ツンベアー', 5, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/614.ogg'),
    ('Hexagel.png', 'Hexagel', 'Cryogonal', 'フリージオ', 5, 'Commun', 'Ice', 'Aucun', 'sons/pokemon/615.ogg'),
    ('Escargaume.png', 'Escargaume', 'Shelmet', 'チョボマキ', 5, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/616.ogg'),
    ('Limaspeed.png', 'Limaspeed', 'Accelgor', 'アギルダー', 5, 'Commun', 'Bug', 'Aucun', 'sons/pokemon/617.ogg'),
    ('Limonde.png', 'Limonde', 'Stunfisk', 'マッギョ', 5, 'Commun', 'Ground', 'Electric', 'sons/pokemon/618.ogg'),
    ('Kungfouine.png', 'Kungfouine', 'Mienfoo', 'コジョフー', 5, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/619.ogg'),
    ('Shaofouine.png', 'Shaofouine', 'Mienshao', 'コジョンド', 5, 'Commun', 'Fighting', 'Aucun', 'sons/pokemon/620.ogg'),
    ('Drakkarmin.png', 'Drakkarmin', 'Druddigon', 'クリムガン', 5, 'Commun', 'Dragon', 'Aucun', 'sons/pokemon/621.ogg'),
    ('Gringolem.png', 'Gringolem', 'Golett', 'ゴビット', 5, 'Commun', 'Ground', 'Ghost', 'sons/pokemon/622.ogg'),
    ('Golemastoc.png', 'Golemastoc', 'Golurk', 'ゴルーグ', 5, 'Commun', 'Ground', 'Ghost', 'sons/pokemon/623.ogg'),
    ('Scalpion.png', 'Scalpion', 'Pawniard', 'コマタナ', 5, 'Commun', 'Dark', 'Steel', 'sons/pokemon/624.ogg'),
    ('Scalproie.png', 'Scalproie', 'Bisharp', 'キリキザン', 5, 'Commun', 'Dark', 'Steel', 'sons/pokemon/625.ogg'),
    ('Frison.png', 'Frison', 'Bouffalant', 'バッフロン', 5, 'Commun', 'Normal', 'Aucun', 'sons/pokemon/626.ogg'),
    ('Furaiglon.png', 'Furaiglon', 'Rufflet', 'ワシボン', 5, 'Commun', 'Normal', 'Flying', 'sons/pokemon/627.ogg'),
    ('Gueriaigle.png', 'Gueriaigle', 'Braviary', 'ウォーグル', 5, 'Commun', 'Normal', 'Flying', 'sons/pokemon/628.ogg'),
    ('Vostourno.png', 'Vostourno', 'Vullaby', 'バルチャイ', 5, 'Commun', 'Dark', 'Flying', 'sons/pokemon/629.ogg'),
    ('Vaututrice.png', 'Vaututrice', 'Mandibuzz', 'バルジーナ', 5, 'Commun', 'Dark', 'Flying', 'sons/pokemon/630.ogg'),
    ('Aflamanoir.png', 'Aflamanoir', 'Heatmor', 'クイタラン', 5, 'Commun', 'Fire', 'Aucun', 'sons/pokemon/631.ogg'),
    ('Fermite.png', 'Fermite', 'Durant', 'アイアント', 5, 'Commun', 'Bug', 'Steel', 'sons/pokemon/632.ogg'),
    ('Solochi.png', 'Solochi', 'Deino', 'モノズ', 5, 'Commun', 'Dark', 'Dragon', 'sons/pokemon/633.ogg'),
    ('Diamat.png', 'Diamat', 'Zweilous', 'ジヘッド', 5, 'Commun', 'Dark', 'Dragon', 'sons/pokemon/634.ogg'),
    ('Trioxhydre.png', 'Trioxhydre', 'Hydreigon', 'サザンドラ', 5, 'Commun', 'Dark', 'Dragon', 'sons/pokemon/635.ogg'),
    ('Pyronille.png', 'Pyronille', 'Larvesta', 'メラルバ', 5, 'Commun', 'Bug', 'Fire', 'sons/pokemon/636.ogg'),
    ('Pyrax.png', 'Pyrax', 'Volcarona', 'ウルガモス', 5, 'Commun', 'Bug', 'Fire', 'sons/pokemon/637.ogg'),
    ('Cobaltium.png', 'Cobaltium', 'Cobalion', 'コバルオン', 5, 'Commun', 'Steel', 'Fighting', 'sons/pokemon/638.ogg'),
    ('Terrakium.png', 'Terrakium', 'Terrakion', 'テラキオン', 5, 'Commun', 'Rock', 'Fighting', 'sons/pokemon/639.ogg'),
    ('Viridium.png', 'Viridium', 'Virizion', 'ビリジオン', 5, 'Commun', 'Grass', 'Fighting', 'sons/pokemon/640.ogg'),
    ('Boréas.png', 'Boréas', 'Tornadus', 'トルネロス', 5, 'Commun', 'Flying', 'Aucun', 'sons/pokemon/641.ogg'),
    ('Fulguris.png', 'Fulguris', 'Thundurus', 'ボルトロス', 5, 'Commun', 'Electric', 'Flying', 'sons/pokemon/642.ogg'),
    ('Reshiram.png', 'Reshiram', 'Reshiram', 'レシラム', 5, 'Commun', 'Dragon', 'Fire', 'sons/pokemon/643.ogg'),
    ('Zekrom.png', 'Zekrom', 'Zekrom', 'ゼクロム', 5, 'Commun', 'Dragon', 'Electric', 'sons/pokemon/644.ogg'),
    ('Démétéros.png', 'Démétéros', 'Landorus', 'ランドロス', 5, 'Commun', 'Ground', 'Flying', 'sons/pokemon/645.ogg'),
    ('Kyurem.png', 'Kyurem', 'Kyurem', 'キュレム', 5, 'Commun', 'Dragon', 'Ice', 'sons/pokemon/646.ogg'),
    ('Keldeo.png', 'Keldeo', 'Keldeo', 'ケルディオ', 5, 'Commun', 'Water', 'Fighting', 'sons/pokemon/647.ogg'),
    ('Meloetta.png', 'Meloetta', 'Meloetta', 'メロエッタ', 5, 'Commun', 'Normal', 'Psychic', 'sons/pokemon/648.ogg'),
    ('Genesect.png', 'Genesect', 'Genesect', 'ゲノセクト', 5, 'Commun', 'Bug', 'Steel', 'sons/pokemon/649.ogg')
  `;


  const insertQueryRequest = `
    INSERT INTO Request (Title, SQL_Request, Image) VALUES
    ("Joueurs de Raimon", "SELECT Name FROM Entity WHERE Licence = 'Inazuma Eleven'", "inazuma.png"),
    ("Champions de League of legends", "SELECT Name FROM Entity WHERE Licence = 'League of legends'", "lol.png"),
    ("Pokémon 1G", "SELECT Name FROM Entity WHERE Licence = 'Pokémon 1G'", "pokemon.png"),
    ("Valeurs de test", "SELECT Name FROM Entity WHERE Licence = 'Test'", "Les valeurs sont 1 et 2.png")
    ;
  `;

  const insertQueryForm = `
    INSERT INTO Form (Title, Option, Text) VALUES
    ("Des pouvoirs !", "1", "Ce serait bien si on pouvait avoir des pouvoirs pour embêter nos adversaires pendant la partie !"),
    ("On voit pas le dernier perso annoncé", "4", "Lorsque le dernier personnage est cité il n'apparait pas derrière nous dans l'écran de victoire");
  `;



  db.serialize(() => {
    db.run(insertQueryLogs, (err) => {
      if (err) {
        console.error('Erreur lors de l\'insertion des données initiales dans Logs :', err.message);
      } else {
        console.log('Données des Logs insérées avec succès.');
      }
    });

    db.run(insertQueryEntity, (err) => {
      if (err) {
        console.error('Erreur lors de l\'insertion des données initiales dans Entity :', err.message);
      } else {
        console.log('Données des Entity insérées avec succès.');
      }
    });


    db.run(insertQueryForm, (err) => {
      if (err) {
        console.error('Erreur lors de l\'insertion des données initiales dans Form :', err.message);
      } else {
        console.log('Données des Form insérées avec succès.');
      }
    });

    db.run(insertQueryRequest, (err) => {
      if (err) {
        console.error('Erreur lors de l\'insertion des données initiales dans Request :', err.message);
      } else {
        console.log('Données des Request insérées avec succès.');
      }
    });
  });
}

module.exports = db;
